### ISSUE TITLE
OS-specific installation instructions not loading

### ISSUE THREAD

**Issue by o-alquimista** [yarnpkg/website#1016]
The OS-specific instructions are not showing up. The request for them on `<select>` change is not returning results. It just keeps on "Loading...". See screenshot.

I tried with uBlock Origin disabled too. It still didn't work.
I also tried this on an Android phone, through the Firefox browser. Same problem.

![Captura de tela de 2019-10-21 14-02-42](https://user-images.githubusercontent.com/25424263/67226914-7a4a8600-f40c-11e9-9461-dc99cacd3f0b.png)

**Comment by o-alquimista** [comment]
For some reason, Markdown isn't working in here. I can't submit the screenshot.

**Comment by Daniel15** [comment]
Huh, that's weird... The page doesn't use AJAX, just J(avaScript). All the content should already be there on load, the dropdowns just switch the visible div. 🤔

**Comment by Haroenv** [comment]
can you see errors in the console?

**Comment by o-alquimista** [comment]
> Huh, that's weird... The page doesn't use AJAX, just J(avaScript). All the content should already be there on load, the dropdowns just switch the visible div. thinking

I just assumed it was AJAX. Are you having this same problem or is it just me?


> can you see errors in the console?

Yes, i'll attach a screenshot:
![Captura de tela em 2019-10-22 09-32-19](https://user-images.githubusercontent.com/25424263/67286179-4ffdd480-f4af-11e9-9e90-b416cf5c8515.png)
`ReferenceError: webpackJsonp is not defined` seems to be where it stops working.

**Comment by Haroenv** [comment]
That's quite odd, I can't replicate this unfortunately :(

**Comment by o-alquimista** [comment]
I tried with Chromium, I did a fresh install of Ubuntu today, same result.

**Comment by Haroenv** [comment]
Where are you located?

**Comment by o-alquimista** [comment]
> Where are you located?

Brazil. I'm not on a VPN

**Comment by humodz** [comment]
Same issue, I'm in Brazil too. For now I'm using the web archive version: [](http://web.archive.org/web/20191018090457/https://yarnpkg.com/en/docs/install/)

**Comment by Daniel15** [comment]
Someone messaged the Yarn page on Facebook about this too.

@o-alquimista - What does the first error message in your screenshot mean? The yellow one.

**Comment by Daniel15** [comment]
Also what happens if you go directly to this URL: https://yarnpkg.com/js/build/vendor.45ef444780b1f9bbd78f.js. Does it load some code, or does it show an error message?

**Comment by o-alquimista** [comment]
> Also what happens if you go directly to this URL: https://yarnpkg.com/js/build/vendor.45ef444780b1f9bbd78f.js. Does it load some code, or does it show an error message?

This is what I see:

![Captura de tela de 2019-10-22 16-37-49](https://user-images.githubusercontent.com/25424263/67324795-83aa2000-f4ea-11e9-8f6e-766cfc334be2.png)

**Comment by Daniel15** [comment]
@Haroenv  - Could you please take a look if you have some time? If not, I can take a look a bit later. I'm not sure why it's redirecting the JS URL to `/en/js/build/....`. I wonder if something is up with Netlify's CDN just in Brazil.

**Comment by o-alquimista** [comment]
It's working for me now. I can no longer reproduce it.

**Comment by Haroenv** [comment]
I've reached out to netlify (@swyx), but they didn't know what could have caused it. I'll assume it was a fluke since I can't replicate it, but I hope it doesn't happen again. Don't hesitate to reach out here if you have such issue
