### ISSUE TITLE
Spanish translations!

### ISSUE THREAD

**Issue by montogeek** [yarnpkg/website#102]
Hi!

I will start translating the docs to Spanish!

Stay tuned :D

**Comment by thejameskyle** [comment]
Woah wait don't, not yet. The translations are going to be managed by Crowdin. I haven't finished setting that up

**Comment by montogeek** [comment]
Oh!

This will no longer apply? https://github.com/yarnpkg/website/blob/master/en/org/translations.md

**Comment by thejameskyle** [comment]
I updated those, they were not correct

**Comment by tunnckoCore** [comment]
What should be done to start the translations? I mean, can we start translating and push changes? Or we should wait CrowdIn? I'm interested in Bulgarian translation.

**Comment by forresst** [comment]
Me too for french

**Comment by ribeiroevandro** [comment]
I'm also interested in translating into Brazilian Portuguese.

**Comment by montogeek** [comment]
@thejameskyle any update?

**Comment by forresst** [comment]
See https://crowdin.com/project/yarn

**Comment by Haroenv** [comment]
http://i18n.yarnpkg.com 😄
