### ISSUE TITLE
Update install instructions for fish shell

### ISSUE THREAD

**Issue by mtjn** [yarnpkg/website#1027]
I couldn't open a pull request because I couldn't find the file to edit for this page: https://yarnpkg.com/en/docs/install#debian-stable

The recommended technique for setting PATH in fish is to use `fish_user_paths` like so:

`set -U fish_user_paths (yarn global bin) $fish_user_paths`

c.f. https://fishshell.com/docs/current/tutorial.html#tut_path and https://wiki.archlinux.org/index.php/Fish#Setting_fish_as_default_shell

Thanks!

**Comment by Haroenv** [comment]
the source is here https://github.com/yarnpkg/website/blob/master/lang/en/docs/_installations/unix_path_setup.md
