### ISSUE TITLE
install.sh script may not clean up gpg-agent processes

### ISSUE THREAD

**Issue by jayaddison** [yarnpkg/website#1029]
During the `install.sh` script, GPG is used to verify the integrity of the downloaded release, which is great.

There are some [reports](https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288) of stalled builds in Travis CI when `yarn` is installed during build process - particularly on the **windows** platform, but [potentially](https://github.com/GoogleChrome/lighthouse/pull/10075) also with **linux** platforms.

In many environments, spinning up a `gpg-agent` process is harmless and won't cause any problems after installation completes, but for Travis the fact that processes are still running is probably causing the build to 'wait' until all steps are complete (which in fact, they are - the `gpg-agent` process is just a side effect).

It looks like `gpgconf --kill gpg-agent` is [one possible way](https://superuser.com/questions/1075404/how-can-i-restart-gpg-agent#1150399) to clean up the daemon once it's no longer required.  Perhaps this can be added after the [verify](https://github.com/yarnpkg/website/blob/ad15aa4735bb4cfb79221bf583aeae22c7e30ce4/install.sh#L73) command runs, so that the process is removed once no longer required.

**Comment by jayaddison** [comment]
cc @Daniel15

**Comment by Daniel15** [comment]
Thanks for the report! Your PR seems good to me.

**Comment by jayaddison** [comment]
Closing this alongside the associated PR; thanks for the review & commentary - I'll re-open in future if this seems to cause any problems.
