### ISSUE TITLE
Add docs for "flat" package.json field

### ISSUE THREAD

**Issue by justinfagnani** [yarnpkg/website#103]
I didn't see the `"flat"` option mentioned here: https://yarnpkg.com/en/docs/package-json or https://yarnpkg.com/en/docs/creating-a-package

The flat option in package.json was added here: https://github.com/yarnpkg/yarn/commit/06e81aae8ebe38c33d98724cd6e16dc5786cc1f9

There are two main points to cover: `flat: true` in the top level package.json triggers a flat installation. `flat: true` in a dependency throws if it's installed in a non-flat installation.

**Comment by aij** [comment]
FWIW, looks like this is already fixed by PR #162

**Comment by Daniel15** [comment]
Yeah, looks like #162 solved this :)
