### ISSUE TITLE
Support TypeScript JSX in markdown files

### ISSUE THREAD

**Issue by rozsival** [yarnpkg/website#1036]
Yarn website cannot parse markdown code examples tagged as `typescript jsx`, however, Github or NPM websites can parse and display those properly.

For example, see the difference in package overview for [@wavevision/class-name](https://github.com/wavevision/class-name):

- [Yarn](https://yarnpkg.com/en/package/@wavevision/class-name)
- [NPM](https://www.npmjs.com/package/@wavevision/class-name)

**Comment by Haroenv** [comment]
https://next.yarnpkg.com/package/?@wavevision/class-name, this seems to have been fixed in v2 of the website. I'm not sure why this would not be recognised as a fenced code block 🤔

**Comment by rozsival** [comment]
@Haroenv Ok, what can I do now? Any suggestions?

Though the link you posted shows the markdown alright, the production version of yarnpkg.com does not.

**Comment by rozsival** [comment]
The `typescript jsx` tag is supported by most IDEs, Github, and NPM website as well. If I tag the code with just `typescript`, ten the JSX tags are not parsed and highlighted correctly.

**Comment by Haroenv** [comment]
Yes, the problem isn't you, it's the website's markdown parser which seems to not take it in account.

**Comment by Haroenv** [comment]
If you _really_  want a solution with the current yarn site before we fix it, you can go with `tsx` as the language tag

**Comment by rozsival** [comment]
Ok, thanks for the tip. I'll use the `tsx` tag for now.

**Comment by rozsival** [comment]
It seems the issue has been resolved.

**Comment by Haroenv** [comment]
this was fixed in v2 indeed
