### ISSUE TITLE
Main yarn website has switched to V2, links broken

### ISSUE THREAD

**Issue by IanVS** [yarnpkg/website#1039]
I tried to open the focused workspaces blog article from a google link, and got a 404 now that the main website seems to have switched over to the v2 docs.  And I don't see any way to get to the old V1 docs...

**Comment by Daniel15** [comment]
@arcanis links to blog posts on the new site should probably redirect to the legacy site?

**Comment by Daniel15** [comment]
Meanwhile you can find the old site at https://legacy.yarnpkg.com/en/

**Comment by IanVS** [comment]
Thanks, it might be good to put that link somewhere easy-to-find, since I imagine that many people will still want to try to find the old docs.

**Comment by arcanis** [comment]
Redirect is up, and the legacy website is referenced in the header (I know, there's a typo, fix on its way 😄).

**Comment by IanVS** [comment]
Ah, I tried clicking the header, but it goes to https://github.com/yarnpkg/berry.  And I didn't read closely enough to realize there was a link at the end.  Might be worth underlying, and hyperlinking to the legacy docs.  Just an idea.  Thanks!
