### ISSUE TITLE
Translated Page is 404 on https://classic.yarnpkg.com

### ISSUE THREAD

**Issue by azu** [yarnpkg/website#1042]
Translated pages are 404.

Examples

- https://classic.yarnpkg.com/ja/
- https://classic.yarnpkg.com/fr/

## Reproduce Steps

1. Visit https://classic.yarnpkg.com/lang/en/
2. Select translated page on the menu

<img width="259" alt="image" src="https://user-images.githubusercontent.com/19714/73810126-cfbe6d80-4818-11ea-9910-39cb00833909.png">

3. Got 404 Not found

## 📝 Notes

Probably, This issue is related with " Site redirecting to /lang/en/ instead of /en/ #1031 "

**Comment by Daniel15** [comment]
I'll look into this.

**Comment by Daniel15** [comment]
This should be OK now.

**Comment by azu** [comment]
Thanks.
I confirm it.

**Comment by XyLyXyRR** [comment]
It's still 404 right now.

**Comment by heng1025** [comment]
> It's still 404 right now.

https://deploy-preview-989--yarnpkg.netlify.app/

**Comment by XyLyXyRR** [comment]
> > It's still 404 right now.
> 
> https://deploy-preview-989--yarnpkg.netlify.app/

This one works fine.
