### ISSUE TITLE
Is there any documentation for "yarn dev"

### ISSUE THREAD

**Issue by songyuc** [yarnpkg/website#1067]
Hi, guys,
I am learner of **yarn**, and I want to know what file the command "yarn dev" would call in this repo,   [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate).
It use `yarn dev` to start the app in the dev environment, as
![图片](https://user-images.githubusercontent.com/27288110/88012999-e39f2700-cb4d-11ea-968c-eb15b68ebbe2.png)
So which file this command would call? 
Does it refer to this line, "dev" as
![图片](https://user-images.githubusercontent.com/27288110/88013095-1d702d80-cb4e-11ea-921a-6e7ebcad3d89.png)

Any answer or idea will be appreciated!

**Comment by heng1025** [comment]
May be docs is wrong

**Comment by Haroenv** [comment]
yarn <script> runs the <script>, in this case the "dev" script. It's documented here: https://yarnpkg.com/cli/run#examples and  https://classic.yarnpkg.com/en/docs/cli/run for v1
