### ISSUE TITLE
Missing navigation

### ISSUE THREAD

**Issue by montogeek** [yarnpkg/website#113]
Hi!

When following the website docs this page https://yarnpkg.com/en/docs/cli/generate-lock-entry does not have the bottom navigation, others page do

**Comment by cpojer** [comment]
Mind sending a PR? We might be missing an import vars or something.

**Comment by montogeek** [comment]
Sure!

**Comment by akshatjain1995** [comment]
@JoelMarcey Can i take this issue to solve?

**Comment by montogeek** [comment]
@akshatjain1995 Go ahead, I am a bit busy today :)

**Comment by akshatjain1995** [comment]
Thank you @montogeek

**Comment by akshatjain1995** [comment]
@montogeek  this issue is solved!! how to proceed further can u explain me!! i m new to the open source!

**Comment by thejameskyle** [comment]
https://github.com/yarnpkg/website/blob/master/en/docs/cli/generate-lock-entry.md

This has a different page `id` than https://github.com/yarnpkg/website/blob/master/_data/guides.yml#L54

Update the id in that markdown file and it should be fixed

**Comment by JoelMarcey** [comment]
@akshatjain1995 Did you solve the issue locally (on your machine, for example)? If so, you can send a pull request. 

https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by akshatjain1995** [comment]
@JoelMarcey yeah sir! Thank you for the information!

**Comment by akshatjain1995** [comment]
@thejameskyle i have edited the following file https://github.com/yarnpkg/website/blob/master/en/docs/cli/generate-lock-entry.md

as u can see that the self-update page is also replacing the `-` with `_`
