### ISSUE TITLE
RSS Link is dead

### ISSUE THREAD

**Issue by NiloCK** [yarnpkg/website#1132]
The post at https://classic.yarnpkg.com/blog/2018/02/15/nohoist/ contains an rss link in its `<head>`:

`<link rel="alternate" type="application/rss+xml" title="Yarn" href="https://yarnpkg.com/feed.xml" />`

But https://yarnpkg.com/feed.xml is a 404.

![image](https://user-images.githubusercontent.com/10780590/132872601-3cb0fd63-49e9-481d-948d-43b888dfcfc0.png)

**Comment by Haroenv** [comment]
Sorry, there's no longer a feed
