### ISSUE TITLE
need `sudo` permission to write tarball file, if as usual user on macOS

### ISSUE THREAD

**Issue by AntSworD** [yarnpkg/website#114]
I think the command of [the document](https://yarnpkg.com/en/docs/install)  need `sudo`

And Yarn is now in `/opt/dist/`  not `/opt/yarn-[version]/` after `tar zvxf yarn-*.tar.gz`

**Comment by Daniel15** [comment]
Which command? The `wget` into `/opt`? You can really extract it wherever you want to :)

Although now we have support for Homebrew, which is probably the preferred method of installation on Mac OS.

> And Yarn is now in /opt/dist/ not /opt/yarn-[version]/ after tar zvxf yarn-*.tar.gz

That's an issue with how we  build the tarball, we should probably fix it.

**Comment by AntSworD** [comment]
@Daniel15 this document page has changed
