### ISSUE TITLE
Package not being added to yarnpkg.com registry (but fine on NPM registry)

### ISSUE THREAD

**Issue by hv-pul** [yarnpkg/website#1149]
First off, apologies if this is not the right spot for this issue. I was not sure where registry issues belong.

I have a strange issue with the package https://www.npmjs.com/package/@hv/flying-focus not being available via https://yarnpkg.com/package/@hv/flying-focus

As you can see the package is not made available via the yarn registry, even though it has been published multiple times for the last 24 hours. For testing purposes I have released new versions of [a different package](https://yarnpkg.com/package/@hv/helpers) of ours to see if they were released correctly in the same timeframe. It took a while, but they are now available.

This is an internal package in heavy development, so I just did local releases for now (using `yarn publish` in the CLI). I have not seen any error message.

When running `yarn pack` the resulting tarball is correct and contains all the files that should be published.

Here is my `package.json` for reference:
```
{
	"name": "@hv/flying-focus",
	"version": "0.0.9",
	"license": "ISC",
	"main": "./dist/flying-focus.umd.js",
	"module": "./dist/flying-focus.es.js",
	"exports": {
		".": {
			"import": "./dist/flying-focus.es.js",
			"require": "./dist/flying-focus.umd.js"
		},
		"./css": "./dist/style.css"
	},
	"files": [
		"index.d.ts",
		"/dist"
	],
	"scripts": {
		"dev": "vite",
		"build": "vite build",
		"serve": "vite preview"
	},
	"devDependencies": {
		"vite": "^2.3.3"
	}
}
```

I'd be grateful for any help on that issue :) I hope it's a transient thing, but it might still be something you might want to know about.

**Comment by hv-pul** [comment]
Some more info:

Strangely local installs work for me, but **not** for my coworkers. I have not linked the package or anything. My `yarn.lock` contains this entry:

```
"@hv/flying-focus@^0.0.6":
  version "0.0.6"
  resolved "https://registry.yarnpkg.com/@hv/flying-focus/-/flying-focus-0.0.6.tgz#7b235d181b883fc4bfba89377f75d9f185114128"
  integrity sha512-OOwfbYHavMslnEjZvWu9WUvu/uuzmcYZF5ksP/RC9otTnou4rsyc4YJpe50+0eTPxpAk59/fD1KTxKllPlYBng==
```

Opening https://registry.yarnpkg.com/@hv/flying-focus/-/flying-focus-0.0.6 gives me this though:
```
{"code":"ResourceNotFound","message":"/@hv/flying-focus/-/flying-focus-0.0.6 does not exist"}
```

Opening https://registry.yarnpkg.com/@hv/flying-focus/-/flying-focus-0.0.6.tgz#7b235d181b883fc4bfba89377f75d9f185114128:
```
{"error":"Not found"}
```

My bitbucket build job also fails with this error:
```
error An unexpected error occurred: "[https://registry.yarnpkg.com/@hv/flying-focus/-/flying-focus-0.0.6.tgz:](https://registry.yarnpkg.com/@hv/flying-focus/-/flying-focus-0.0.6.tgz) Request failed \"404 Not Found\"".

**Comment by Haroenv** [comment]
The package is private, and thus doesn't show up in the yarn website, as it doesn't (yet, although I don't think it's really possible with npm apis) use login information to show private packages.

Trying to access packages via url without authorisation headers indeed looks the same as if the package didn't exist.

I'm assuming your colleagues either haven't correctly logged in on their terminal or don't actually have access for their account to the hv organisation.

As this isn't an issue for the yarn website, but for npm support probably, I'll close this issue for now.

Good luck!

**Comment by hv-pul** [comment]
For some reason it is published as private 🤦 
Sorry for the troubles

**Comment by Haroenv** [comment]
No problem! Scoped packages are indeed published as private by default, unless you specify `--access public` while publishing
