### ISSUE TITLE
Site should have og:graph meta tag

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/website#115]
Currently it looks pretty bad when shared on Facebook - There's no image.

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fyarnpkg.com%2F

![](http://ss.dan.cx/2016/10/chrome_11-10.35.44.png)

**Comment by JoelMarcey** [comment]
I am working on this now. Pull request coming hopefully soon.
