### ISSUE TITLE
Modify the structure of the package.json file

### ISSUE THREAD

**Issue by jircdev** [yarnpkg/website#1178]
Nowadays the package.json created by yarn generates the "main" entry point. I think could be a good (and necessary) idea to add "exports" entry.

The exports entry replaces/overwrites the "main" entry points and gives more control over what the package exposes or not. 
Also, the "exports" entry is used to define subpackage settings in different situations as environments or platforms to use.
Nowadays the package.json created by yarn generates the "main" entry point. I think could be a good (and necessary) idea to add "exports" entry.

The exports entry replaces/overwrites the "main" entry points and gives more control over what the package exposes or not. 
Also, the "exports" entry is used to define subpackage settings in different situations as environments or platform

**Comment by Haroenv** [comment]
This is something that can be opened on the yarn/berry repository, not the website :)
