### ISSUE TITLE
<title> of every page is “Yarn”

### ISSUE THREAD

**Issue by bdougherty** [yarnpkg/website#118]
Would be helpful to have the `<title>` match the title of the page.

**Comment by akshatjain1995** [comment]
Members can i solve this issue?

**Comment by JoelMarcey** [comment]
@akshatjain1995 I have a pull request out for this issue already. But there are other open issues both in this repo and the actual [yarn repo](https://github.com/yarnpkg/yarn) as well.

**Comment by akshatjain1995** [comment]
Yaa @JoelMarcey  no problem! will look out for some more interesting issue!
