### ISSUE TITLE
Use installation through npm as default

### ISSUE THREAD

**Issue by iamso** [yarnpkg/website#140]
On the website, under installation, you have different methods to install yarn.
The first thing you say, is that node.js has to be installed, which actually installs npm by default.

So why not have the first method of installation be npm?

Asking people to run a bash script to install yarn, when they could use the much simpler and (from a users perspective) much safer `npm install`, should actually be the alternative method of installation.

It's just a little bit confusing ;)

**Comment by Daniel15** [comment]
Hi @iamso! 

`npm` is not at all well-suited for system-level package management, so we won't be changing this. Here's one of my comments from a few weeks ago:

> Advantages of using the system's native package manager rather than something like `npm install -g yarn`:
>
> - Upgrades are handled the same way as all other software on your system (`apt-get upgrade`). It's not a special snowflake.
> - All the security problems with npm (eg. packages not being signed) make it less than ideal for anything installed system wide. apt-get gives you proper GPG signature verification.
> - Using npm means you're tightly-coupled to npm. If you later want to have a better installation solution, you need to have this awkward transition period where you try to get users to switch to the newer installation method.
> - The setup instructions need the whole weird "*install Node.js first, then ensure npm is up-to-date, then install Yarn*" thing. That'd be like telling people to manually install their npm dependencies 😆 . With a proper package management system, the Yarn package would simply have a dependency on the Node.js package, and "apt-get install yarn" would install both.
> 
> If we want to appeal to people that have limited Node.js experience, we shouldn't make any assumptions that they know anything about the Node.js ecosystem or what "npm" even is.

Also, please see a previous discussion here: https://github.com/yarnpkg/rfcs/issues/9

> The first thing you say, is that node.js has to be installed

Not when using Homebrew, the Linux packages, or the Windows Chocolatey package. All of these will automatically install Node.js if it's not already installed. You do **not** need to know anything about Node.js to install Yarn and it can be directly installed on a vanilla system 😄 

> which actually installs npm by default.

Not always. Ubuntu's Node.js package has npm in a separate `npm` package, and people using the "standalone" `node.exe` on Windows also don't have npm.

> much safer npm install

Linux packages are significantly safer as they're properly GPG signed. Similarly, the Windows installer will be Authenticode signed (although we're not quite there yet, I'm still getting that set up).

Given this, I'm going to close this task, but please feel free to provide any questions or feedback you may have!

Thank you for trying Yarn! 😄
