### ISSUE TITLE
yarn init --yes

### ISSUE THREAD

**Issue by kittens** [yarnpkg/website#144]

**Comment by ashleygwilliams** [comment]
does this actually work? (doesn't seem to in the version i just downloaded) if/when it works i would happily write docs for it :) it's a fave feature of mine in npm and i'd be amped to help out with yarn.

**Comment by thejameskyle** [comment]
https://github.com/yarnpkg/yarn/pull/873

**Comment by ashleygwilliams** [comment]
that's excellent news.

**Comment by cpojer** [comment]
(closing in favor of the PR)
