### ISSUE TITLE
docs/configuration: Add config articles for common CI tools

### ISSUE THREAD

**Issue by suitupalex** [yarnpkg/website#148]
It might be useful to have articles on how to properly setup your `.travis.ci`, `circle.yml`, etc. so that they actually use yarn when installing and running tests.

**Comment by Haroenv** [comment]
You might take in account that for Travis for example by doing it like [this](https://github.com/micromata/http-fake-backend/blob/master/.travis.yml), you're adding the install of `yarn` to the time your CI runs, so it might not be faster anymore because of that overhead.

**Comment by Haroenv** [comment]
This can be closed now https://yarnpkg.com/en/docs/install-ci

**Comment by suitupalex** [comment]
👍

**Comment by Daniel15** [comment]
Oh cool, I didn't even realise there was an issue for this :)
