### ISSUE TITLE
Add table mapping npm commands to yarn commands

### ISSUE THREAD

**Issue by thejameskyle** [yarnpkg/website#16]
Something like:

| npm | yarn |
| --- | --- |
| `npm install` | `yarn install` |
| `npm install [package]` | **_(Intentionally not supported)**_ |
| `npm install --save [package]` | `yarn add [package]` |
| `npm install --save-dev [package]` | `yarn add --dev [package]` |
| ... | ... |

**Comment by markstos** [comment]
Can this ticket be closed now that there's a comparison table live on the website?

https://yarnpkg.com/docs/migrating-from-npm#toc-cli-commands-comparison
