### ISSUE TITLE
Translate to Chinese, we can't wait! 中文文档翻译

### ISSUE THREAD

**Issue by xcatliu** [yarnpkg/website#176]
Hi,

I love yarn 😍 , and want to help to translate the website to Chinese.
I noticed that the website itself has a support for i18n, and you have a plan to support multiple languages:
https://yarnpkg.com/en/org/translations

> We’re not quite set up yet (will take a few more days, but once that happens we’ll be able to translate via CrowdIn).

But we can't wait to show this awesome tool to Chinese! We have some volunteers that want to contribute to the translation.

Here is the forked repo: https://github.com/xcatliu/yarnpkg-website
As well as the demo link: http://yarnpkg.xcatliu.com/zh-Hans/

It's still not completed yet. After we finished translate, we'll create a pull request for this.

I write this issue also for people who searched for the Chinese translation. If you are interested in this. Please contact me!

Thanks!

**Comment by Daniel15** [comment]
Thank you so much for working on this! @thejameskyle is going to set up an awesome translation system for the website, and we'd love for you to assist us! I'll let James speak to the timelines and when we'll actually have the translation system up and running.

Thank you for contributing! 😄

**Comment by yanyu0517** [comment]
I and my partner  @shanggqm have create a chinese website, here is the address: [Yarn中文网](http://yarnpkg.top/). We are so glad if you can link the website.
@xcatliu 最近一直在忙，刚看到你发的issue，没来得及回复，请见谅。我们已经完成翻译了，当然水平有限，有些地方翻译的很晦涩，后续我们会持续改进和勘误。不知是否我们可以一起完成？

**Comment by shanggqm** [comment]
Yarn is an amazing project that perfectly addresses the pain points we have been working on, and we hope that our translation work will contribute to Yarn's popularity in China。

**Comment by tatthien** [comment]
We want to translate Yarn to Vietnamese also. Notify us when you guy have already finished set up the translation system. 

Thank you.

**Comment by xcatliu** [comment]
@yanyu0517 @shanggqm Great job!
Let's discuss how to merge our work here: https://github.com/yanyu0517/yarnpkgcn/issues/2

**Comment by kaddopur** [comment]
any update for applying CrowdIn?

**Comment by Daniel15** [comment]
It looks like @thejameskyle has set up Crowdin at https://i18n.yarnpkg.com/ so I think you can start translating there now!

**Comment by Daniel15** [comment]
I'm going to close this out since the Crowdin project is up now, and a translated site will be up in the near future. Thanks for your support!

**Comment by jerry855202** [comment]
any plan for traditional chinese? or is this currently simplified only
I see cht on crowdin, and could see myself putting some time into cht translation based on chs, and change some terms used in zh-tw.

**Comment by Daniel15** [comment]
Hey @jerry855202! Since Traditional Chinese is available on CrowdIn, please feel free to start translating. Once the translation is nearly complete, we can launch the translation on the site :)
