### ISSUE TITLE
Specifying that yarn is meant for node.js, npm, etc....

### ISSUE THREAD

**Issue by jpartain89** [yarnpkg/website#184]
Is it just me or does the entire website only mention this info in passing in a few places?? Should this not be, like, a 2nd header or in the detailed description of your site... Like, the details that get published to google and everywhere? Because I definitely had to search to see WHAT this system "managed", as in was it for every language or what?

Super confusing...

**Comment by ungoldman** [comment]
Already brought up in #133, the decision was to keep it as is. I agree it's confusing but I think the intention is for yarn to be "language agnostic."

**Comment by jpartain89** [comment]
Ok... but even then, to me?? That compounds the confusion..... THAT even isn't mentioned anywhere.... Should that NOT be Prominently featured? Like that should be a primary Google AdSearch-style campaign item...

**Comment by thejameskyle** [comment]
I don't think it's necessary to go overboard on being language-agnostic at this point. Closing for the same reason as #133
