### ISSUE TITLE
Automate bumping latest_version in config.yml

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/website#187]
Logic should be something like: If there's a newer release on Github, **and** it has **all** artifacts attached (`.tar.gz`, `.deb`, `.rpm`, and `.msi`), then bump `latest_version` and commit it. It's very important to not bump latest_version until all artifacts have been uploaded to the release.

**Comment by Daniel15** [comment]
This also needs to handle rollbacks - If we intentionally downgrade the version number (eg. from 0.17.0 to 0.16.1 like we did recently), it should not automatically bump it forward again.

**Comment by Haroenv** [comment]
Is this handled by your @DanBuild now, @Daniel15 ?

**Comment by Daniel15** [comment]
Yes! :D
