### ISSUE TITLE
Wish: Add equivalent (or lack of) of "npm rebuild" to the Migrating from NPM guide.

### ISSUE THREAD

**Issue by markstos** [yarnpkg/website#192]
Thanks.

**Comment by starInEcust** [comment]
+1

**Comment by arunaspask** [comment]
+1

**Comment by markstos** [comment]
@starInEcust @arunaspask Note the "plus smiley face" icon above each comment. Please use that to "thumbs up" a comment you like in the future which registers the same support, but without all the noise and emails that "+1" comments generate.

**Comment by kittens** [comment]
The equivalent command is:

```
$ yarn install --force
```
