### ISSUE TITLE
Add package searching

### ISSUE THREAD

**Issue by thejameskyle** [yarnpkg/website#194]
npms.io has an api that we could use to power a simple package searching site for npm packages:

https://api.npms.io/v2/search?from=0&q=babel&size=25

I don't want to just point to the npms.io site because I don't really like the scoring mechanism or even adding "scores" to packages in general.

It might be cool to even display the READMEs on the yarn website

**Comment by Daniel15** [comment]
It looks like their API doesn't have CORS headers, so we'd need to proxy it.

**Comment by tunnckoCore** [comment]
@thejameskyle why need to couple the things? Is it not enough to use them separately? Everyone has its own purpose and way. I don't get such need.

**Comment by dhruvdutt** [comment]
@Daniel15 Is anybody working on this?

**Comment by thejameskyle** [comment]
I was hoping to work on it at some point, I'm in a slack channel with the npms.io folks

**Comment by dhruvdutt** [comment]
Have a look at this library. [https://github.com/wires/npm-keywordsearch](url)
Please update here what the npms.io guys say. I would like to help on this.

**Comment by thejameskyle** [comment]
We don't have a server-side component to the yarn website at this point in time so we cannot use node libraries

**Comment by Daniel15** [comment]
We shouldn't need a server-side component as long as npms.io can add CORS support to their API :D
