### ISSUE TITLE
Clarify whether yarn uses yarn.lock when a package is installed as a dependency

### ISSUE THREAD

**Issue by MajorBreakfast** [yarnpkg/website#215]
https://yarnpkg.com/en/docs/yarn-lock should mention whether yarn considers the yarn.lock files of dependencies or just the yarn.lock of the current package/project. I can provide a PR, but as of now I don't know the answer myself :) (I have only a guess: No, because things would conflict)

**Comment by thejameskyle** [comment]
Yarn does not make any use of `yarn.lock` files in nested dependencies as that would mean we cannot de-duplicate anything in the tree, it'd be slower, and it would cause a ton of unnecessary extra work to keep nested dependencies up to date.

**Comment by MajorBreakfast** [comment]
Alright. I'll provide a PR in <30min

**Comment by MajorBreakfast** [comment]
Done
