### ISSUE TITLE
Add FAQ section

### ISSUE THREAD

**Issue by donaldpipowitch** [yarnpkg/website#219]
It looks like the website has no FAQ section. It would be nice to add one, which can be searched by the main search input in the header, too.

There was a Medium article some days ago which collected [a lot of interesting questions](https://medium.com/@boennemann/questions-i-wish-yarn-had-answered-on-day-1-ec0db745807#.rbfgiudbp).

I'd especially like to know, what happens if modules from custom private registries are installed by yarn. Are they somewhere cached by yarn online, so they could maybe exposed to others...?

**Comment by thejameskyle** [comment]
I would prefer to avoid having a FAQ if we can better answer the questions as part of the normal flow of the website. Having a FAQ is like giving up.

Let's try to do that for a while, if you think something can be better answered in the normal documentation open an issue

**Comment by donaldpipowitch** [comment]
IMHO the "best" way would be to answer these questions in the first place and _then_ figure out how to display them to the user in the best way. Content first.

> Having a FAQ is like giving up.

Why? Honest question. FAQ is straight forward. Sire, Google Search and Co. all develop features to ask questions naturally and get answers back. Asking a question seems very natural to me, if you look for a _specific_ answer. The "normal documentation" is more linear. You probably need to search more to find the answer you need.

**Comment by thejameskyle** [comment]
That is the whole point of having search on the website

<img width="632" alt="screen shot 2016-10-28 at 11 06 17 am" src="https://cloud.githubusercontent.com/assets/952783/19817019/9a771410-9cfe-11e6-9691-3a6d3c91b511.png">

**Comment by donaldpipowitch** [comment]
So you have questions with answers in your docs, but they are not called FAQ, but included in different sections of the docs. I'm fine with that ;)

Then I'll create a separate issue for every question I have which could be of interest for everyone.

**Comment by donaldpipowitch** [comment]
Sorry, if my title was misleading. I was not asking for an FAQ for the sake of having a "real" FAQ. It was a more general question to answer some things in the docs I couldn't find like "What happens if modules from custom private registries are installed by yarn. Are they somewhere cached by yarn online, so they could maybe exposed to others...?".

It doesn't matter to me "how" this is presented in the docs at the end.
