### ISSUE TITLE
Error on make command

### ISSUE THREAD

**Issue by dhruvdutt** [yarnpkg/website#238]
I get the following error on executing `make` command after `gem install bundler`

OS: Ubuntu 16.04

```
root@root:/media/dhruvdutt/Dev/Practice Projects/website# make
make[1]: Entering directory '/media/dhruvdutt/Dev/Practice Projects/website'
Cloning into '_sass/bootstrap'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:twbs/bootstrap.git' into submodule path '_sass/bootstrap' failed
Makefile:9: recipe for target 'install' failed
make[1]: *** [install] Error 128
make[1]: Leaving directory '/media/dhruvdutt/Dev/Practice Projects/website'
Makefile:5: recipe for target 'start' failed
make: *** [start] Error 2
```

**Comment by thejameskyle** [comment]
Do you not have [SSH setup with GitHub](https://help.github.com/articles/generating-an-ssh-key/)?

**Comment by Daniel15** [comment]
@thejameskyle A lot of people use HTTPS with GitHub, as it's what they show by default and [recommend in their documentation](https://help.github.com/articles/which-remote-url-should-i-use/). We should change the Bootstrap URL to either `git://github.com/twbs/bootstrap.git` or `https://github.com/twbs/bootstrap.git`, as both of these URLs allow anonymous access (whereas the `git@` one always requires auth). A read-only version of Bootstrap's repo is fine for our use cases 😛

**Comment by dhruvdutt** [comment]
It's working now! I've configured SSH. Thanks!
