### ISSUE TITLE
Prominently display latest version number somewhere

### ISSUE THREAD

**Issue by glenjamin** [yarnpkg/website#252]
As mentioned in https://github.com/yarnpkg/yarn/issues/1730

It's currently non-trivial to figure out what the latest version of yarn is from the website, it'd be good to throw this number in the header somewhere.

It would also be good to provide some guidance during or near the installation instructions about how to upgrade `yarn` to the latest version - does `self-update` work regardless of the install method?

**Comment by Daniel15** [comment]
I've been meaning to add this while working on the nightly builds (show both the nightly version number and the stable version number).

>  does self-update work regardless of the install method? 

Not yet, https://github.com/yarnpkg/yarn/issues/1139 covers that.

**Comment by thejameskyle** [comment]
@Daniel15 oh sorry, I added it to the navbar already

**Comment by Daniel15** [comment]
No worries @thejameskyle!  😄 

I think we should mention it on the download page too.

**Comment by Haroenv** [comment]
Where should this be shown?

1. Before the copy

<img width="1173" alt="screen shot 2017-04-03 at 15 26 12" src="https://cloud.githubusercontent.com/assets/6270048/24611308/f79cfc28-1881-11e7-9fdf-ec4f717a974b.png">

2. In the header

<img width="1175" alt="screen shot 2017-04-03 at 15 27 42" src="https://cloud.githubusercontent.com/assets/6270048/24611353/1e028e0a-1882-11e7-9a80-52405bf3f72f.png">

3. In the copy itself?

**Comment by vvo** [comment]
2. Seems better indeed
