### ISSUE TITLE
Navigation Hamburger expanding problem

### ISSUE THREAD

**Issue by sorcamarian** [yarnpkg/website#254]
Hi,

I noticed a problem on the [homepage](https://yarnpkg.com/) in small screens view, on click the menu is expanding and imediatelly collapsing.

Please check this video: https://youtu.be/cG3IfUZf8W4

**Comment by thejameskyle** [comment]
This likely has to do with me pulling the bootstrap repo

**Comment by thejameskyle** [comment]
Fixed, sorry about that
