### ISSUE TITLE
Nightly installation animation collapses after expanding

### ISSUE THREAD

**Issue by pornel** [yarnpkg/website#258]
![2016-11-12 23_41_29](https://cloud.githubusercontent.com/assets/72159/20242737/a4f3c494-a931-11e6-8a9d-10b4a3dad4a8.gif)

^ that's not gif restarting, the section does collapse immediately like that.

I'm using Chrome 55.0.2841.0 canary (64-bit) OS X 10.11.

**Comment by thejameskyle** [comment]
Fixed, sorry about that
