### ISSUE TITLE
Merge in nightly builds page

### ISSUE THREAD

**Issue by thejameskyle** [yarnpkg/website#259]
https://nightly.yarnpkg.com/

@Daniel15 Any reason this can't be a page on the normal website? The styles and layout have already gone out of sync.

If there's something dynamic you could just turn it into a JSON api that we can fetch from.

**Comment by Daniel15** [comment]
It was mostly a placeholder while I was building out the infra 😄 

> If there's something dynamic

Yeah, the list of files is dynamic.

I can make it a JSON thing instead though. That seems like a reasonable idea.

**Comment by thejameskyle** [comment]
Yeah I just noticed this and thought we should do that

<img width="1082" alt="screen shot 2016-11-12 at 4 23 48 pm" src="https://cloud.githubusercontent.com/assets/952783/20242913/6d30f1ea-a8f4-11e6-8728-3cb6ebbacc7a.png">

**Comment by Daniel15** [comment]
The other option is dynamically pulling in the header and footer from the Yarn site and caching it. I like that the page is so fast to load since it doesn't use JavaScript to load the list of files 😛

**Comment by thejameskyle** [comment]
lol, you in that big of a rush?

**Comment by thejameskyle** [comment]
btw, where does this code live?

**Comment by Daniel15** [comment]
> lol, you in that big of a rush?

Gotta go fast! ;P

> btw, where does this code live?

It's in the releases repo at the moment. When I get a chance, I'll add some docs to the repo explaining how everything fits together.
