### ISSUE TITLE
Mention "JavaScript" or "Node" on the frontpage above the fold

### ISSUE THREAD

**Issue by laughinghan** [yarnpkg/website#301]
Cool project! But, have you noticed you don't mention JavaScript or Node anywhere on the frontpage, and "npm" only in the bottom left corner amongst a bunch of other text? If I'm understanding correctly, `yarn` is intended to replace only `npm` and `bower`, right, not `apt-get` or `pacman` or Homebrew?

**Comment by markstos** [comment]
Good point. Reminds of all the websites that advertise that they are a "local business", but forget to tell you where they are local to. 

> FAST, RELIABLE, AND SECURE DEPENDENCY MANAGEMENT. *(for JavaScript)*

**Comment by thejameskyle** [comment]
See #133

**Comment by laughinghan** [comment]
Haha right, or like "Area Man"
