### ISSUE TITLE
CircleCI instructions seem out of date

### ISSUE THREAD

**Issue by philfreo** [yarnpkg/website#323]
It seems that https://yarnpkg.com/en/docs/install-ci#circle-tab was written before 2 rounds of Yarn improvements by Circle.

The thread linked to on the page above goes to https://discuss.circleci.com/t/preinstall-yarn/7353, which indicates yarn comes preinstalled now. See also https://github.com/circleci/circleci-docs/issues/487

**Comment by Daniel15** [comment]
CircleCI have their own documentation now:
https://circleci.com/docs/install-and-use-yarn/. We should remove the docs
on the Yarn site and point to their docs instead. Pull requests are
appreciated :)

**Comment by felicianotech** [comment]
Opened/referenced PR ^.
