### ISSUE TITLE
[bug] Unicode chars missing in PT-BR translation (only .md files)

### ISSUE THREAD

**Issue by degroote22** [yarnpkg/website#365]
It appers that only ASCII is shown on the website.
Go to https://yarnpkg.com/docs/cli/bin and look at the first sentence:
`Mostra a localizao da pasta bin do yarn.`

it hsould be

`Mostra a localização da pasta bin do yarn.`

All .md files seems to have the issue, like at https://yarnpkg.com/org/code-of-conduct and .html files are ok (home page for instance)

**Comment by Daniel15** [comment]
This looks correct in Crowdin (https://i18n.yarnpkg.com/translate/yarn/192/en-ptbr) so I guess it's an issue with the syncing. @thejameskyle could you please have a look? Thanks!

**Comment by degroote22** [comment]
@Daniel15 Yup. I was the one that translated this page btw :)

**Comment by Daniel15** [comment]
It looks like this was fixed at some point.
