### ISSUE TITLE
404 pages

### ISSUE THREAD

**Issue by JulienBourgain** [yarnpkg/website#379]
Go on : https://yarnpkg.com/ (the browser is redirected to https://yarnpkg.com/lang/en/)

So after that, in the header, click on getting started or doc => it's work

But if you click on package or blog and after you click on getting started or doc => 404 page

Going to  package or blog remove the language information in the URL. I think it's the cause of the bug :)

**Comment by Daniel15** [comment]
I can't replicate this issue, are you still seeing it?

**Comment by JulienBourgain** [comment]
I think it has been fixed 
duplicated : #367
PR : #368

**Comment by Daniel15** [comment]
Thanks for the confirmation, I'll close this issue :)
