### ISSUE TITLE
Why in  .gitignore ignoring lang directory?

### ISSUE THREAD

**Issue by hookszhang** [yarnpkg/website#381]
I want contribute chinese document, what should i do?

**Comment by Daniel15** [comment]
Hello @hookszhang! Translations are handled on a service called "CrowdIn". If you'd like to help translate the site, please go to https://i18n.yarnpkg.com/.

Currently, Chinese Simplified is 92% translated, and Chinese Traditional is 10% translated. Once they get close to 100%, the translations will be available on the live site.

Thank you!
