### ISSUE TITLE
click on 'Docs' return 404 when coming from 'Blog' or 'Packages'

### ISSUE THREAD

**Issue by alfredbez** [yarnpkg/website#385]
1. https://yarnpkg.com/en/
1. Click on 'Blog' or 'Packages' (top-left navigation)
1. Click on 'Getting Started' or 'Docs'

![image](https://cloud.githubusercontent.com/assets/1001186/23126016/07c88514-f775-11e6-8491-569f2d8398e5.png)

Looks like [{{url_base}}](https://github.com/yarnpkg/website/blob/08f6bf95e0ecba171290d7ad5818c0692a3a8043/_includes/navigation.html#L17) is empty. Take a look at [this](https://github.com/yarnpkg/website/blob/d69f4f0b95fc04ec05fe7d0561edf0f2d380e553/_includes/vars.html), too.

**Comment by vvo** [comment]
Cannot reproduce right now, can you have a look again?

**Comment by alfredbez** [comment]
![yarn-bug](https://cloud.githubusercontent.com/assets/1001186/23296977/cf32b520-fa77-11e6-8d52-0a572f14e918.gif)

**Comment by vvo** [comment]
What's the language of your browser? Mine is english

Here's my screencast, we are missing something obvious I guess.

![kapture 2017-02-24 at 9 55 35](https://cloud.githubusercontent.com/assets/123822/23314593/74ca18ee-fa77-11e6-9b86-03e6df8799d4.gif)

**Comment by alfredbez** [comment]
> What's the language of your browser? Mine is english

Min is German.  
It works, when I change the language to english.

**Comment by vvo** [comment]
Ok then that's the issue I guess, when the browser language is not part of the available translations, this fails I guess.

**Comment by donaldpipowitch** [comment]
FYI: This also breaks the link to "Contributing" and probably several others. When I visit https://yarnpkg.com/org/contributing/ I get a 404 (german browser as well).

Sadly I have _no idea_ how Jekyll works, but this is probably a nice and easy bug to fix which would help a lot of users. I guess there just needs to be some `|| 'en'` or any kind of default language somewhere in the correct place :)
