### ISSUE TITLE
French translation for linux install  breaks the commands

### ISSUE THREAD

**Issue by nicolas-t** [yarnpkg/website#387]
Hello,

this page in french : https://yarnpkg.com/fr/docs/install#linux-tab

you have this command : 
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo « deb https://dl.yarnpkg.com/debian/ stable main » | sudo tee /etc/apt/sources.list.d/yarn.list
```
which is not working (no line break, and fancy quotes), meanwhile, the one in english : 
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
```

is working well.

**Comment by vvo** [comment]
Made an edit on crowdin (http://i18n.yarnpkg.com/) but having hard time understanding if I need to click on save/publish/request somewhere on the interface. :)

**Comment by Haroenv** [comment]
Looks like your update went through and this can be closed
