### ISSUE TITLE
Not possible to link to a specific OS tab on the install page

### ISSUE THREAD

**Issue by edmorley** [yarnpkg/website#413]
**STR:**
1. Visit https://yarnpkg.com/en/docs/install
2. Use the in-page tab navigation to switch to an OS other than the OS you're currently running
3. Copy the URL
4. Open that URL in a new tab

**Expected:**
The newly opened install page honours the OS selection in the URL.
ie: Even on OS X / Windows, https://yarnpkg.com/en/docs/install#linux-tab will show the Linux tab.

**Actual:**
If https://yarnpkg.com/en/docs/install#linux-tab is visited on Windows, the page instead shows the Windows tab, and the URL in the location bar is reset to https://yarnpkg.com/en/docs/install#windows-tab

Note also that the location bar uses URLs of form `...#linux-tab` whereas the link target for the in-page navigation tabs uses `...#linux`. However regardless of which is used, the issue still occurs.

Many thanks :-)

**Comment by edmorley** [comment]
The functionality is controlled by:
https://github.com/yarnpkg/website/blob/66acf52e8f096bef1d74dce6895874f64b3f44d4/js/src/install.js
https://github.com/yarnpkg/website/blob/66acf52e8f096bef1d74dce6895874f64b3f44d4/js/src/lib/deeplink.js

It looks like:
a. `handleOS()` should not be called if there is an anchor hash in the URL already.
b. The anchor hashes in `handleOS()` and the `div` `id`s in [install.html](https://github.com/yarnpkg/website/blob/66acf52e8f096bef1d74dce6895874f64b3f44d4/_layouts/pages/install.html) should be made consistent.

**Comment by vvo** [comment]
Hi @edmorley, it seems you dig this a lot already, would you mind sending a pull request that would help solve this issue? There's an auto preview deploy for every PR so we will even be able to check together the new behaviour you implement.
