### ISSUE TITLE
Status page

### ISSUE THREAD

**Issue by reyrodrigez** [yarnpkg/website#416]
would be nice to see if there's any issue with the registry or the dl service.

**Comment by Daniel15** [comment]
Interesting idea. Maybe we could use something like https://cachethq.io/, I've seen a few projects use that.

**Comment by reyrodrigez** [comment]
@Daniel15 we used https://www.statuspage.io/ in the past

**Comment by Daniel15** [comment]
@reyrodrigez - statuspage.io looks pretty expensive. Cachet is open-source 😃

**Comment by reyrodrigez** [comment]
you're right, I should click first... Let me know if I can help you guys implementing this.

**Comment by Haroenv** [comment]
Always happy to have contributions

**Comment by Daniel15** [comment]
Added https://status.yarnpkg.com/
