### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by vmazare** [yarnpkg/website#422]
The URL https://yarnpkg.com/en/docs/offline-mirror seems to be not found.

**Comment by Daniel15** [comment]
@vmazare  Are you still having issues? The link works for me.

**Comment by sejoker** [comment]
@Daniel15 @vmazare this one still returns 404 https://yarnpkg.com/en/docs/cli/

**Comment by Daniel15** [comment]
@sejoker  That link works for me:
![](http://ss.dan.cx/2017/03/chrome_21-14.31.02.png)

**Comment by sejoker** [comment]
that's weird, it works for me as well, although it reproduced both in Safari, Chrome, FF.

I have a screenshot from console:
![screen shot 2017-03-21 at 9 38 18 pm](https://cloud.githubusercontent.com/assets/125466/24172111/ec583f2e-0e7e-11e7-9f90-f57f0034ca7c.png)

**Comment by sejoker** [comment]
probably it's VPN related, never mind.

**Comment by spencer-brown** [comment]
Looks like this is a trailing slash issue:
- https://yarnpkg.com/en/docs/cli works.
- https://yarnpkg.com/en/docs/cli/ does not work.

Unfortunately, https://yarnpkg.com/en/docs/ links to the broken URL.

**Comment by vmazare** [comment]
@Daniel15 It seems to work now, not sure what was the reason

**Comment by spencer-brown** [comment]
@vmazare this is not fixed - please see my comment at the bottom describing the failure case due to trailing slash issues.

**Comment by Daniel15** [comment]
@spencer-brown - Interesting.. All of those URLs work for me.

**Comment by vmazare** [comment]
@spencer-brown The URLs you mentioned work for me too

**Comment by spencer-brown** [comment]
@Daniel15 weird... the broken links 404 for me in Chrome, Chrome incognito, and Safari.
