### ISSUE TITLE
404 at index in PT-BR

### ISSUE THREAD

**Issue by johnnyasantoss** [yarnpkg/website#424]
Hello!
Apparently some links are broken :/
I accessed [https://yarnpkg.com/pt-BR/][yarn] and got this
[![404 Error](http://image.prntscr.com/image/6ed17d0202b048c9b8a251b764f8a12f.png)][yarn]

[yarn]: https://yarnpkg.com/pt-BR/

**Comment by daltones** [comment]
Same here.

Apparently it's an issue with all languages except `en`.

**Comment by johnnyasantoss** [comment]
It is working now :|
Okay, thanks!
