### ISSUE TITLE
Page cli/list not found

### ISSUE THREAD

**Issue by hotsoft-desenv2** [yarnpkg/website#456]
Hi,

after run: 'yarn list -h' the page suggested is: "  Visit https://yarnpkg.com/en/docs/cli/list for documentation about this command." but the page is not found.

is the expected?

Thanks.

**Comment by ndresx** [comment]
The target page for this is https://yarnpkg.com/en/docs/cli/ls, which apparently hasn't been renamed yet. There are a couple of PRs that should address this issue though, like https://github.com/yarnpkg/website/pull/377.

**Comment by gsklee** [comment]
`yarn list` is the correct name of the command; `-h` as an option to this command is invalid.

**Comment by Haroenv** [comment]
closed by #377
