### ISSUE TITLE
Update Codeship installation instructions

### ISSUE THREAD

**Issue by rmm5t** [yarnpkg/website#458]
Re: https://yarnpkg.com/lang/en/docs/install-ci/#codeship-tab

> ```
> npm install --global yarn
> ```

Installing yarn via npm is now deprecated and yields an out-of-date version.

This is likely the better approach:

```bash
curl -o- -L https://yarnpkg.com/install.sh | bash
export PATH=$HOME/.yarn/bin:$PATH
```

**Comment by lptn** [comment]
note, it's better to use `--compressed` key, took from https://yarnpkg.com/lang/en/docs/cli/self-update/
```sh
curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
```
