### ISSUE TITLE
Installation Guide Not Working 

### ISSUE THREAD

**Issue by levlaz** [yarnpkg/website#474]
On Safari and Firefox (on macOS)

On this page: https://yarnpkg.com/en/docs/install#linux

Clicking on any of the platform links does not pull up the associated documentation. It simply continues to say: " Select your platform above "

<img width="789" alt="screen shot 2017-05-01 at 11 22 28 pm" src="https://cloud.githubusercontent.com/assets/7981032/25606255/4d7ad486-2ec5-11e7-9fb8-4b3216b2d5fd.png">

**Comment by Daniel15** [comment]
Hmm, works for me in both Chrome and Firefox on Windows 10 (sorry, I don't have a Mac available to test on Mac OS).

**Comment by Haroenv** [comment]
I think I can replicate it. Weird though, definitely worked earlier

**Comment by levlaz** [comment]
Not sure if its relevant but the browser console log shows this: 

```
[Error] Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404) (vendor.4d200760f3726e42677f.js, line 0)
[Error] ReferenceError: Can't find variable: webpackJsonp
	Global Code (common.f40766f4f8048492c8d6.js:1)
[Error] ReferenceError: Can't find variable: webpackJsonp
	Global Code (install.5f619da91e349dc0fab6.js:1)
```

**Comment by Haroenv** [comment]
Yes, that could be part. All the other js works for you?

**Comment by levlaz** [comment]
@Haroenv Yeah looks like its just that one thats not loading: 

<img width="302" alt="screen shot 2017-05-01 at 11 49 41 pm" src="https://cloud.githubusercontent.com/assets/7981032/25606924/e593f8ee-2ec8-11e7-8c9b-da8b7d0b0e55.png">

**Comment by levlaz** [comment]
Full URL: https://yarnpkg.com/js/build/vendor.4d200760f3726e42677f.js

**Comment by Haroenv** [comment]
Seemed to have some weird caching things. I ran a new build on Netlify and I can't find any missing hashes anymore. Feel free to reopen if it isn't fixed yet.

**Comment by levlaz** [comment]
Thanks so much, working perfectly now.
