### ISSUE TITLE
Render text based changelog

### ISSUE THREAD

**Issue by jcubic** [yarnpkg/website#483]
I have changelog that's simple text file not markdown, the file name is [CHANGELOG](https://github.com/jcubic/jquery.terminal/blob/master/CHANGELOG) not CHANGELOG.md and it seems that [yarn website always render changelog as markdown](https://github.com/yarnpkg/website/blob/d4998493773c6831bee2ea769668814d159e5c23/js/src/lib/Details/index.js#L150) so mine it's broken [jquery.terminal](https://yarnpkg.com/en/package/jquery.terminal).

I can't fix it to replace CHANGELOG by CHANGELOG.md in next version but it would be nice if yarn website support text based changelogs there are may be more packages that have text based changelogs.

**Comment by Haroenv** [comment]
That's a good point, but the version without .md is a lot more popular in my finding with markdown after all. If you've done some more research or a solution, I'd like to hear it

**Comment by jcubic** [comment]
Does the file can be CHANGELOG.md? because I'm in the process of rewriting changelog to markdown. I didn't notice anywhere info about filename in the source code (the variable is not set anywhere in this repo https://github.com/yarnpkg/website/search?utf8=%E2%9C%93&q=changelogFilename&type=

**Comment by Haroenv** [comment]
https://github.com/algolia/npm-search/blob/master/github.js

**Comment by jcubic** [comment]
Thanks, will close then.
