### ISSUE TITLE
add.md: is something missing?

### ISSUE THREAD

**Issue by gsklee** [yarnpkg/website#498]
Between L38 & L40:

> In general, a package is simply a folder with code and a package.json file that describes the contents. You can refer to a package a number of different ways:
> 
> You can also specify packages from different locations:

Is something missing here or is it just bad punctuation?

**Comment by thejameskyle** [comment]
Looks like I fucked it up in this commit https://github.com/yarnpkg/website/commit/e4c9adeeed15e410a700c80c36d8923dd2131d7a

**Comment by gsklee** [comment]
Hmmm looks like a lot of content is missing in the current version? Not sure how much you'd like to add back.

**Comment by thejameskyle** [comment]
If you just want to open a PR we can get it to a good state again

**Comment by gsklee** [comment]
Took a closer look, it seems to be a pure copyediting issue that can be easily cleaned up.
