### ISSUE TITLE
Outdated docs for offline mirror

### ISSUE THREAD

**Issue by asvny** [yarnpkg/website#499]
I think it is outdated for https://yarnpkg.com/blog/2016/11/24/offline-mirror/

Commands like `yarn install –offline` seems to suggest `yarn`

**Comment by bestander** [comment]
--offline and offline mirror are different features.
Looks fine to me.
Feel free to send a PR with a fix if anything seems wrong

**Comment by asvny** [comment]
@bestander 
<img width="699" alt="screen shot 2017-05-17 at 5 56 51 pm" src="https://cloud.githubusercontent.com/assets/5235065/26153715/59c8e496-3b2a-11e7-9fc8-f28edd8b1276.png">

When I ran the command specified in the 3rd point , I got this error 
<img width="697" alt="screen shot 2017-05-17 at 5 56 25 pm" src="https://cloud.githubusercontent.com/assets/5235065/26153738/79e1b94c-3b2a-11e7-8c27-2e8859dbf75e.png">

**Comment by bestander** [comment]
I think it should be `--offline`.
Could you verify and send a PR with a fix pleasE?
