### ISSUE TITLE
`yarn import`

### ISSUE THREAD

**Issue by gsklee** [yarnpkg/website#503]
There seems to be a new command [`yarn import`](https://github.com/yarnpkg/yarn/pull/2580/commits/016f3192248af68bb6aff9d0c272a6d9a8b83a24) that's absent on the website.

**Comment by bestander** [comment]
Yeah, would be great to add a section here https://yarnpkg.com/en/docs/migrating-from-npm.
@gsklee, are you up to write a small note there?

**Comment by gsklee** [comment]
I'd like to, but I haven't really used the command, so let's see if @xdissent wanna handle this first.

**Comment by bestander** [comment]
It is a community effort, so anyone's help is very much welcome.
Thanks, @gsklee, for raising issues about missing docs.

**Comment by gsklee** [comment]
Gonna tracking this in #507 instead.
