### ISSUE TITLE
package.json "config" field

### ISSUE THREAD

**Issue by gsklee** [yarnpkg/website#506]
[https://yarnpkg.com/en/docs/package-json#toc-config](https://yarnpkg.com/en/docs/package-json#toc-config)

Could it be elaborated some more here, like how do we reference these config values inside our scripts?

**Comment by bestander** [comment]
Not sure where it is coming from.
Manifest type does not declare config in package.json.

**Comment by gsklee** [comment]
npm's explanation on the same `package.json` field: https://docs.npmjs.com/files/package.json#config

Seems like if you do `npm config set [something] [some-value]` it goes into `.npmrc`, but if you do `npm config set [package-name]:[something] [some-value]` it goes into this package.json "config" field?

**Comment by bestander** [comment]
Maybe, I think Yarn has not implemented this feature yet.
Is it needed if .yarnrc is cascading?
