### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by hobakill** [yarnpkg/website#519]
```
curl -o- -L https://yarnpkg.com/install.sh
```

&&

```
➔ http --headers https://yarnpkg.com

http: error: Request timed out (30s).
```

times out.

**Comment by bkyarger** [comment]
I'm getting Error 522, Connection timed out from Cloudflare when trying to pull https://yarnpkg.com/latest.tar.gz

**Comment by Haroenv** [comment]
Noticing it too, might be related to GitHub downtime earlier today

**Comment by webloem** [comment]
My heroku builds using yarn are failing because of the site returning a 522.

**Comment by mgol** [comment]
Yarn tarball URLs are returning 502, e.g.: https://yarnpkg.com/downloads/0.24.6/yarn-v0.24.6.tar.gz

This breaks our builds.

**Comment by ldabiralai** [comment]
Could be related to this?

https://twitter.com/netlifystatus/status/869932943627624451
https://netlifystatus.com/

We're also having issues

**Comment by Haroenv** [comment]
http://yarnpkg.netlify.com/en/ seems to be up intermittently, will update when resolved 😄

**Comment by zygimantas** [comment]
It would be nice if we could download the latest release artifact directly from github, as latest.msi/zip

**Comment by khadirbaaoua** [comment]
well github was down as well earlier ...

**Comment by hobakill** [comment]
I'm getting responses now:

```
➔ http --headers https://yarnpkg.com
HTTP/1.1 200 OK
Age: 0
CF-RAY: 367b626eba0e251f-ORD
Cache-Control: public, max-age=0, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Wed, 31 May 2017 16:42:06 GMT
Server: cloudflare-nginx
Set-Cookie: __cfduid=da1b8aac83fd21caf203856da652f16f21496248926; expires=Thu, 31-May-18 16:42:06 GMT; path=/; domain=.yarnpkg.com; HttpOnly
Transfer-Encoding: chunked
Vary: Accept-Encoding
```

**Comment by nickstanish** [comment]
For anyone using yarn on heroku, I added this issue to see if we can get some redundancy in installing the yarn binary: https://github.com/heroku/heroku-buildpack-nodejs/issues/418

cc @webloem

**Comment by khadirbaaoua** [comment]
website seems to be up again
