### ISSUE TITLE
Installation using `curl` gets version 0.24.6! Is it intended?

### ISSUE THREAD

**Issue by badersur** [yarnpkg/website#544]
When I execute the command:

```terminal
curl -o- -L https://yarnpkg.com/install.sh | bash
```

I'm expecting to obtain the latest version (v0.26.1 as [releases page](https://github.com/yarnpkg/yarn/releases) says) but I get 0.24.6.

Is it a bug or an intended behaviour?!

OS: Ubuntu 17.04

**Comment by Daniel15** [comment]
@bestander @arcanis Was it intended that v0.26.1 be marked as stable? It's marked as stable on GitHub but not anywhere else (the release steps weren't run for it)

**Comment by bestander** [comment]
Let's mark 0.27 stable on Monday

**Comment by badersur** [comment]
Now I notice that the docs says 0.24.6 is the stable version!

I think it's worth mentioning which version of yarn the script will install; the statement:
> You can install Yarn by running the following code in your terminal:

is not clear! Is it the latest stable version, the most stable verified version, or a specific stable version?

Also, after looking at the script, I've noticed that the option `--rc` is **not** documented. Should I document it or is it left intentionally?!

**Comment by Daniel15** [comment]
The script installs the latest stable version, as shown on the site at https://yarnpkg.com/. It gets the version number from https://yarnpkg.com/latest-version, which is the source of truth for the latest version number.

> Also, after looking at the script, I've noticed that the option `--rc` is **not** documented.

It should be documented, it was likely just an oversight :) The `--nightly` tag is documented at https://yarnpkg.com/en/docs/nightly but we might not have any docs on how to install a RC.

**Comment by daprahamian** [comment]
Question: were `0.25.x`-`0.27.x` released, but just not stable? Or should they have been marked stable to begin with?

**Comment by Daniel15** [comment]
They're all unstable (RC) releases, as far as I know.

**Comment by badersur** [comment]
I was thinking about changing the installation doc to be like:

> You can also get a release candidate version by running the following code in your terminal:
    ```sh
    curl -o- -L https://yarnpkg.com/install.sh | sh -s -- --rc
    ```
    Or a specific version by running the following:
    ```sh
    curl -o- -L https://yarnpkg.com/install.sh | sh -s -- --version [version]
    ```
    See the releases for possible versions.

But maybe there're other places to add this info about `--rc` and it can be obtained using the `--version` tag so I'm thinking it's not so necessary to add it.

Even though `--rc` is too convenient :)

**Comment by Daniel15** [comment]
0.27.3 was just published and will be up shortly, so I'm closing this  as the original issue was resolved.

@badersur  - Feel free to create a separate issue for the doc updates if you like. Or, submit a pull request and we can throw some ideas around :)

**Comment by Daniel15** [comment]
We should document how to install a particular version via Debian package too:
```
sudo apt-get install yarn=0.24.6-1
```

**Comment by badersur** [comment]
@Daniel15  I've just grabbed it. Thanks for letting me know about it and for answering my questions :)

But I have some concerns...

in your website: 
> Stable: v0.24.6  • Release Candidate v0.27.3

In github releases:
v0.27.3 labelled as **latest release**

and I can't notice any differences between 0.27.2  & 0.27.3 from GitHub's compare changes:

https://github.com/yarnpkg/yarn/compare/v0.27.3...master
https://github.com/yarnpkg/yarn/compare/v0.27.2...master

and .24 is not marked as stable! (I think most people will go to github to see the releases - at least this is what I do normally! but from now on I'm going to use the `--rc` tag!)

**Comment by badersur** [comment]
Is it necessary to add `-1` to version number while installing using `apt-get`? because I don't see versions with this format!

Is specifying version number using package managers is only supported on Debian-related distributions?

Personally, I don't think I can participate in updating the docs now...

**Comment by BYK** [comment]
@badersur I think that's just how Debian packages work (the additional `-1`).

**Comment by badersur** [comment]
@BYK I see! Thanks for the info :)
