### ISSUE TITLE
Can't browse projects' files

### ISSUE THREAD

**Issue by 0joshuaolson1** [yarnpkg/website#545]
I've tried unrelated packages. I get this in Chrome:
'Could not load file listing: Failed to execute 'fetch' on 'Window': Illegal invocation'

**Comment by Daniel15** [comment]
@Haroenv Do you have any ideas here? It looks like all the `fetch` calls are throwing "Failed to execute 'fetch' on 'Window': Illegal invocation", including the calls that load data from GitHub.

**Comment by Haroenv** [comment]
That sounds weird. I'll try to find something

**Comment by bestander** [comment]
Can confirm that issue is there

<img width="1164" alt="screen shot 2017-06-29 at 2 00 25 pm" src="https://user-images.githubusercontent.com/2121048/27710124-73a435b2-5cd3-11e7-9eed-602e7fa504a5.png">

**Comment by Haroenv** [comment]
That happens when you click before it's loaded fully, right?

**Comment by bestander** [comment]
It happens every time I clock on Browse Files and does not go away

**Comment by Haroenv** [comment]
Arg that's annoying. I'll try to replicate it somehow

**Comment by Daniel15** [comment]
I originally thought LastPass was causing this, as they appear to be shimming `window.fetch`. The only clue I got was a string "lpsubmit" in the injected code. However, even after disabling LastPass (or using an Incognito window), the error still occurs.

If I do exactly the same `fetch` call in the browser console, it works. 🤔

**Comment by Haroenv** [comment]
I really can’t replicate this in Safari. It works perfectly 🌐 What extensions do you have @bestander 


EDIT: ah so ultra weird, it’s happening in Chrome

**Comment by Haroenv** [comment]
https://github.com/QuentinRoy/lightmill-js/commit/9c2b5293f9570ac6b2533f69c8c8647da8cedc0c

**Comment by Daniel15** [comment]
Interesting, looks like it was patched in unfetch:
https://github.com/developit/unfetch/pull/47/files. Is there a new release
we could upgrade to?

--
Regards,
Daniel Lo Nigro
http://dan.cx/ | Twitter <http://twitter.com/Daniel15> | Facebook
<http://www.facebook.com/daaniel>

**Comment by Haroenv** [comment]
Yes, was just going to try that, either importing `unfetch` instead of `fetch`

**Comment by Haroenv** [comment]
Fixed with #556
