### ISSUE TITLE
excerpt bug

### ISSUE THREAD

**Issue by willin** [yarnpkg/website#548]
![wx20170627-141623](https://user-images.githubusercontent.com/1890238/27573203-4afdd748-5ad6-11e7-9dad-3ae4df505d2f.png)

**Comment by Haroenv** [comment]
That's a bug in the npm registry, there's no way for us to find if the description is original or excerpted from the README

see https://github.com/npm/normalize-package-data/blob/3dc7756af20b3b1b24c6d75302448ca3659e0a65/lib/fixer.js#L226

**Comment by Haroenv** [comment]
This can be fixed by showing nothing if it's an excerpt, since the README is just below it anyway...

Anyway, for your own package you can fix it by adding a description in package.json
