### ISSUE TITLE
Add short permalink to package info page

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/website#549]
https://yarnpkg.com/en/package/react should display `https://yarn.fyi/react` somewhere, so that people know that it works as a nice short permalink to the page. 

@Haroenv do you have any design ideas for this? Perhaps we could put it above the home page link in the right column.

**Comment by Haroenv** [comment]
That's a good idea, I mocked it up like this:

<img width="1204" alt="screen shot 2017-06-27 at 10 19 23" src="https://user-images.githubusercontent.com/6270048/27577763-2b2806d6-5b22-11e7-86c3-309445a87a3b.png">

What do you think ?

**Comment by vvo** [comment]
+ copy button? :)

**Comment by Haroenv** [comment]
possible @vvo, would that be relevant for all of the sidebar links then?

**Comment by vvo** [comment]
Nope, the other sidebar links you want to go there (click and change page).

Only this one, you are already on the page, so you ONLY want to copy it I believe.
