### ISSUE TITLE
`latest` version downloaded by yarn install script does not match `latest` on GitHub

### ISSUE THREAD

**Issue by spencer-brown** [yarnpkg/website#553]
My team is using the Yarn install script hosted at https://yarnpkg.com/install.sh to install Yarn in CI, but the `latest` version installed by that script does not match the `latest` version on [Yarn's GitHub](https://github.com/yarnpkg/yarn/releases/tag/v0.25.3).

Why is this? Also, is the version installed by that script guaranteed to be the same as the version shown on the Yarn homepage?

**Comment by Daniel15** [comment]
The version listed on the Yarn website (https://yarnpkg.com) is the source of truth for the latest version number. There's a few releases incorrectly marked as stable on GitHub.

@bestander @arcanis  - Can we bump 0.27.x to stable soon?

**Comment by bestander** [comment]
Nope, still testing, I think there are 2 regressions we have found.

**Comment by Daniel15** [comment]
0.27.3 was just published and will be up shortly.
