### ISSUE TITLE
No Documentation for `yarn workspace`

### ISSUE THREAD

**Issue by daprahamian** [yarnpkg/website#563]
Running `yarn v0.27.5` with `workspaces-experimental true`

I wanted to try the experimental `yarn workspace` command, but there is no documentation.

`yarn help workspace` links to https://yarnpkg.com/en/docs/cli/workspace, which does not exist.

**Comment by Daniel15** [comment]
cc @arcanis, @bestander

**Comment by bestander** [comment]
A blog post is coming in July.
I'll keep the task open until it's up

**Comment by vicapow** [comment]
should be able to close this now. https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/

**Comment by bestander** [comment]
With the blog post we can close this.
Once I have a spare moment I'll link the blog post from the Docs secion, https://github.com/yarnpkg/website/issues/573

**Comment by richburdon** [comment]
> yarn help workspace

Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.

Returns 404

**Comment by Haroenv** [comment]
Good point, let’s add that page

**Comment by robdonn** [comment]
Any progress on this issue?

**Comment by bestander** [comment]
Nope :(
If anyone jumps in and fixes #573 that would be great

**Comment by kassens** [comment]
This is fixed: https://yarnpkg.com/en/docs/cli/workspace
