### ISSUE TITLE
problem scss 

### ISSUE THREAD

**Issue by jubayed** [yarnpkg/website#582]
i want to install this website. 

problem:
 `Happy[1]: All set; signaling webpack to proceed.
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    File to import not found or unreadable: bootstrap/scss/bootstrap.scss. Load path: /srv/myforum/myforumbd.github.io/_sass on line 24
jekyll 3.2.1 | Error:  File to import not found or unreadable: bootstrap/scss/bootstrap.scss.
Load path: /srv/myforum/myforumbd.github.io/_sass on line 24
   873 modules

`

**Comment by Haroenv** [comment]
You need to have the git submodules:

```sh
git submodule update --recursive --remote
```
