### ISSUE TITLE
Update performance comparison benchmarks

### ISSUE THREAD

**Issue by BYK** [yarnpkg/website#588]
The performance comparison benchmarks we publish are a bit outdated and there aren't any automated ways to update them. Until we have one, we may wanna link people to https://github.com/pnpm/node-package-manager-benchmark

Another alternative would be to leverage GitHub's api to make that page look nicer and natively on our website.

**Comment by Haroenv** [comment]
see also #372

**Comment by BYK** [comment]
Duplicate of #372.
