### ISSUE TITLE
URL for files on detail page

### ISSUE THREAD

**Issue by Haroenv** [yarnpkg/website#594]
could also be `?files` or something, and it should open the files view once a page is loaded from that URL. A query string will be easier, since then we just need to pass another prop to the Detail component, which then renders the files, if needed

**Comment by Daniel15** [comment]
This is a good idea 😃

**Comment by Haroenv** [comment]
A think to keep in mind here, is that the files view rely on the package already being fetched from Algolia, if you load it before loading the other metadata, it won't work. If this is made, that timing issue could be fixed at the same time

**Comment by leonardosnt** [comment]
I got it working: ![peek 2017-12-30 17-02](https://user-images.githubusercontent.com/13869336/34456745-341c00a2-ed86-11e7-9b25-6bcb46498dce.gif)

Here is the code: https://github.com/leonardosnt/website/commit/04b1e0dcf39699d57c1f2fcfe7890b2bf6158069
What do you think?

**Comment by Haroenv** [comment]
That looks great @leonardosnt, are you opening up a pr?

**Comment by leonardosnt** [comment]
Sure, here it is: #748
