### ISSUE TITLE
Update Installation Instructions - CentOS / Fedora / RHEL

### ISSUE THREAD

**Issue by burgwyn** [yarnpkg/website#595]
The current installation instructions for Node.js on CentOS / Fedora / RHEL fail

```sh
curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
```

Based on research, the [instructions from NodeSource](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora) are actually

```sh
curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -
```

**Comment by bestander** [comment]
Fixed now

**Comment by Daniel15** [comment]
The old one would have worked fine if you run it as root (ie. run `sudo -i` to get a root terminal, then run it). Thanks for submitting a fix! 👍
