### ISSUE TITLE
yarn link

### ISSUE THREAD

**Issue by cpojer** [yarnpkg/website#60]

**Comment by mattmccray** [comment]
"done!" -- How so? I'm getting the same issue.

`error Couldn't find package "my-local-package" on the "npm" registry.`

**Comment by JohnnyBushy** [comment]
Looks like "yarn link" doesn't work at all :(

**Comment by thejameskyle** [comment]
@JohnnyBushy @mattmccray you're in the wrong repository, this one is for the website

**Comment by mattmccray** [comment]
True, sorry. The appropriate issue seems to be: https://github.com/yarnpkg/yarn/issues/1297
