### ISSUE TITLE
Browse files doesn't seem to work

### ISSUE THREAD

**Issue by dguo** [yarnpkg/website#614]
Hi, I tried opening the file listing for https://yarnpkg.com/en/package/qs, and I got an error message: `Could not load file listing: Unexpected token < in JSON at position 0`. I got the same thing in incognito mode. Firefox gave me `Could not load file listing: JSON.parse: unexpected character at line 1 column 1 of the JSON data`, and Safari gave me `Could not load file listing: The string did not match the expected pattern.`. I tried other packages (webpack and left-pad), and they produced the same errors for me.

It looks like it's making a request to the GitHub API, and the JSON response looks okay, though I don't see any file info.

**Comment by Daniel15** [comment]
Looks like a breaking change with the Unpkg site. We use their API to retrieve the file listing. I'll ping @mjackson about it.

https://github.com/unpkg/unpkg-website/issues/60

**Comment by mjackson** [comment]
Sorry @dguo, my bad! Should be fixed now :)

**Comment by dguo** [comment]
Thanks to both of you for the quick fix!
