### ISSUE TITLE
typo in Selective dependency resolutions | Limitations & Caveats

### ISSUE THREAD

**Issue by workjalexanderfox** [yarnpkg/website#639]
https://github.com/yarnpkg/website/blob/master/lang/en/docs/selective-version-resolutions.md

"Nested packages may nor work properly."
to
"Nested packages may not work properly."

**Comment by Daniel15** [comment]
Would you like to submit a pull request to fix it? You can edit the file directly on GitHub - Click the pencil icon at the top right

**Comment by workjalexanderfox** [comment]
yeah, thought I would have to fork and create PR.

**Comment by Daniel15** [comment]
Fixed by #640. Thanks!
