### ISSUE TITLE
the wrong URLs in the top menu after visited /blog

### ISSUE THREAD

**Issue by pierreneter** [yarnpkg/website#642]
**reproduce**

* Visit: https://yarnpkg.com/blog/
* Click any link in the top menu bar except for the logo and icons on the right

Incorrect URLs and 404 errors.

**Comment by Haroenv** [comment]
oh, thanks for that! That’s because the blog isn’t translated, we should just link to `/en/...` there

**Comment by BYK** [comment]
Should be fixed with #812.
