### ISSUE TITLE
Download count is incorrect for namespaced packages

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/website#644]
https://yarn.pm/@yarnpkg/lockfile shows 0 downloads
https://www.npmjs.com/package/@yarnpkg/lockfile shows 199 downloads.

**Comment by Haroenv** [comment]
Yep, that's an open issue on the crawler: https://github.com/algolia/npm-search/issues/61; scoped packages break the API call if you check the downloads in batch instead of individually. 


Thanks for noticing!

**Comment by Haroenv** [comment]
All packages have downloads now, 10.5k (I had to do a double take) for [yarn.pm/@yarnpkg/lockfile](https://yarn.pm/@yarnpkg/lockfile)
