### ISSUE TITLE
Docs: document the --cwd option

### ISSUE THREAD

**Issue by BYK** [yarnpkg/website#651]

**Comment by Haroenv** [comment]
PR: https://github.com/yarnpkg/yarn/pull/4174

**Comment by rheaditi** [comment]
Hi @Haroenv, 
I'd like to pick this up! 🙂 

Where in the docs do you feel the section pertaining to this makes sense? I've currently added it to the `yarn run` page. However, is there a page that is more appropriate for this? 😄

**Comment by Haroenv** [comment]
The main command page too I think @rheaditi

**Comment by shunia** [comment]
It's been more than one year, so what's next?
I read about the `--cwd` command from comments of the CRA project [here](https://github.com/facebook/create-react-app/blob/4c7c3c5e28b7840de42755a17112804ff5a18c25/packages/create-react-app/createReactApp.js#L314), but found no document for the option here, only this old issue.

**Comment by Haroenv** [comment]
@shunia the text in #774 is correct, but it hasn't been applied to every command. Either we make a new page for global flags, either it needs to be added everywhere
