### ISSUE TITLE
Docs: document `yarn <script>` usage

### ISSUE THREAD

**Issue by BYK** [yarnpkg/website#656]

**Comment by Haroenv** [comment]
This is `yarn run <script>`, but with `run` optional, right?

**Comment by BYK** [comment]
@Haroenv yup :)

**Comment by roryokane** [comment]
Related: [#306 “No `yarn run` shortcuts documented”](https://github.com/yarnpkg/website/issues/306)

**Comment by Haroenv** [comment]
Feel free to contribute wherever you think this makes sense
