### ISSUE TITLE
Auto-focus front page search field

### ISSUE THREAD

**Issue by scarlac** [yarnpkg/website#662]
**Feature proposal:**

![screen shot 2017-09-26 at 19 26 33](https://user-images.githubusercontent.com/895369/30874496-d03f636a-a2f0-11e7-82ca-83d4e00e8949.png)

I propose that the main search field on the front page is focused automatically once the app is mounted, since it's such a prominent feature. It would make the frontpage immediately useful as a search page.

**Comment by Haroenv** [comment]
It’s auto focused at /packages
By the way, you can focus it by typing s or /

Free to more feedback about it

**Comment by scarlac** [comment]
Thanks @Haroenv . Didn't know I could press `s`. Typing `/` doesn't work on a Danish keyboard though. It doesn't have a dedicated key for `/` but have to press Shift+7. Switching to US layout (still with Danish keyboard) doesn't make it work.

I'm closing, as this was not a bug report but more of a feature request.

**Comment by Haroenv** [comment]
Yep, you need to have a dedicated key, it wouldn't make much sense otherwise.

The main reason we don't focus on all pages, is because the /en/docs has two search bars

Let's focus it on the main page though, it makes sense
