### ISSUE TITLE
Cli menu in French is broken

### ISSUE THREAD

**Issue by clement-escolano** [yarnpkg/website#665]
Hello,

In the french menu when browsing the documentation, the key `yarn generate-lock-entry ` is repeated (the second one points to `yarn global`) and the `yarn global` key points to `yarn info`.
You can see the screenshot here:
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/11637509/30915525-5a7495fe-a397-11e7-9a45-046765a53d0c.png">

Thank you for this website ;) 

Clément

**Comment by Haroenv** [comment]
This is probably something translated wrong on https://i18n.yarnpkg.com, will take a look

**Comment by Haroenv** [comment]
http://i18n.yarnpkg.com/project/yarn/fr/activity#translation_id=4831

Fixed, will be deployed on next release IIRC

**Comment by clement-escolano** [comment]
Thank you !
