### ISSUE TITLE
Document that `yarn run` no longer needs `--` for args

### ISSUE THREAD

**Issue by roryokane** [yarnpkg/website#666]
The [`yarn run` docs](https://yarnpkg.com/en/docs/cli/run) still say this:

> ### `yarn run [script] [-- <args>]`
> 
> ...
> 
> You can pass additional arguments to your script by using `--`.
> 
>     yarn run test -- -o --watch
> 
> Running this command will execute `jest -o --watch`.

But when I try running a command with that `--`, I see this warning:

~~~
$ yarn run eslint -- --quiet
yarn run v1.0.1
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
...
~~~

> From Yarn 1.0 onwards, scripts don't require `--` for options to be forwarded. In a future version, any explicit `--` will be forwarded as-is to the scripts.

The `yarn run` docs should be updated to reflect this.

_Search keywords:_ hyphen, dash

**Comment by Daniel15** [comment]
Would you like to submit a pull request to update this documentation?

--
Regards,
Daniel Lo Nigro
https://dan.cx/ | Twitter <http://twitter.com/Daniel15> | Facebook
<http://www.facebook.com/daaniel>
