### ISSUE TITLE
Broken images when using relative paths to SVG (compared to PNG)

### ISSUE THREAD

**Issue by smotaal** [yarnpkg/website#692]
*This is a joint issue for both NPM & Yarn caused by how `raw.githubusercontent.com` misidentifies certain file types.*

**TD;LR**

I created a sample package with a README and details:
  * **GitHub**: https://github.com/code-therapy/packages-with-readme-relative-images
  * **NPM**: https://www.npmjs.com/package/@code-therapy/packages-with-readme-relative-images
  * **Yarn**: https://yarnpkg.com/en/package/@code-therapy/packages-with-readme-relative-images

**Recommendations**

* Maybe GitHub can have a cross-origin policy for trusted referrers like npm & yarn.
* Maybe NPM can devise a way for packages to provide README with embedded content.
* Maybe you could use or borrow something from how rawgit handles this.

Thanks

---

NPM issue: npm/marky-markdown#420

**Comment by Daniel15** [comment]
This sounds like a Github bug rather than an npm or Yarn bug. Maybe contact Github support about it?

**Comment by Haroenv** [comment]
this is because of https://github.com/isaacs/github/issues/316

**Comment by smotaal** [comment]
It does sound like it is, but it actually is not… here is why:

* raw.githubusercontent.com (which replaced taw.github.com) does the following:

  > Serves raw file content from your repository
  > *[GitHub's post from April 25, 2014 — New user content domains](https://developer.github.com/changes/2014-04-25-user-content-security/)*

  This is not the same as serves files, which should be properly typed, but rather the raw file content, and it does that by ensuring that you will always get the bytes as they are in the repo.

  They opted to MIME-type images but avoided typing anything that will execute when viewed by anyone which does limit their responsibility legally.

*  What GitHub means by raw (as opposed to rendered) is more clear from the API side when they define the types of Repository Content:

  > *Raw*
  >
  >     application/vnd.github.VERSION.raw
  > 
  > Return the raw contents of a file. This is the default if you do not pass any specific media type.
  >
  > *HTML*
  >
  >     application/vnd.github.VERSION.html
  >
  > For markup files such as Markdown or AsciiDoc, you can retrieve the rendered HTML using the .html media type. Markup languages are rendered to HTML using our open-source Markup library
  >
  > *[Media Types](https://developer.github.com/v3/media/) — GitHub Developer*

* CORS can be a factor (this is all you) that will influence how raw.githubusercontent.com fulfills requests:

  > … I just needed to set a crossOrigin property on my image to get my project working again …
  > *rgrove/rawgit#144*

  While this is not really related to SVG, the only one who can do anything about CORS is the rendering party, so when you convert `![…](…/….svg)` to `<img src="https://raw.githuusercontent.com/…/…/….svg" />` this is where CORS would (or at least could) factor in… Just imagine what it would take if as users we were to file issues with GitHub asking them to change how they respond to certain referring domains on behalf of those domains.

I guess those are a few points to help keep this conversation going. But, from what I've gathered so far, I can safely figure that it takes your involvement since using raw.githubusercontent.com is a design decision that you had to make at some point, and honestly it affects the majority of your user base (even if they decided to PNG over this issue).

**Comment by smotaal** [comment]
@Haroenv yeah… I've gone through that one and it is a lot of information going in all directions, very confusing to figure out how to move forward but I found the github/markup#556 a really good read on what GitHub resorts to in order to manage SVG (which is a static resource that contains dynamic content compared to PNG).

**Comment by smotaal** [comment]
One thing I can recommend as a possible way to force-type with yarn's client-side rendering is to XHR the content into blobs (object-urls) or data-urls (ohhh can have performance impact on users) and use those as src's for the images, but you will probably need to refactor buildImageUrl to async function regardless or return a placeholder and have XHR's load event replace those elements when the content resolves.

**Comment by smotaal** [comment]
@Haroenv BTW I just realized that the last recommendation which I initially assumed applies only internally within github.com and it's direct subdomains also works for `raw.githubusercontent.com`… 

This solves this issue so I hope others can learn about this solution.

You can check out the package on all 3 sites showing new instances with `?sanitize=true` and it works!

**Comment by Haroenv** [comment]
let's add that by default then, thanks for investigating!

**Comment by smotaal** [comment]
Thank you!

**Comment by smotaal** [comment]
So, just wanted to update you guys on the latest on this from my end.

I did a little experiment with offloading the entire rendering to GitHub:

https://codepen.io/daflair/full/aVvGKV

It uses GitHub v3 api, so it would require authentication to avoid rate limiting which is something I am sure Yarn already does for other aspects of the site.

**Comment by Haroenv** [comment]
That's cool @smotaal! unfortunately we found that authenticating is too much hassle, but this would be a nice addition. If you'd like to spend the time figuring out how to get users to authenticate so we can use the GitHub api. The problem we have a little now is that we can't hardcode an api key or similar, because we have more traffic that _one_ api key can handle. Feel free to open another issue for enabling this!

**Comment by Haroenv** [comment]
After reading your comment a second time, I think it might be possible to do it that way to offload the rendering, and get known safe html back. We can maybe enable it as a A/B test 🚀
