### ISSUE TITLE
"change language" icon

### ISSUE THREAD

**Issue by normanzb** [yarnpkg/website#701]
The icon itself reads "Aあ" since あ is Japanese hiragana, I supposed there should be Japanese translation, but it doesn't, this breaks the principle of least astonishment.

**Comment by Haroenv** [comment]
Thanks for your feedback, let's change it, I think we should rather just enable Japanese, since it's almost complete. Maybe you can help with the last parts? 

http://i18n.yarnpkg.com/project/yarn/ja#

I'll take a look how to enable Japanese here too :)

**Comment by Haroenv** [comment]
I just enabled the Japanese translations! thanks everyone in the community and you for reminding us!
