### ISSUE TITLE
README.cn.md instead of regular README.md

### ISSUE THREAD

**Issue by ai** [yarnpkg/website#711]
[PostCSS repo](https://github.com/postcss/postcss) has two README files: `README.md` and `README.cn.md` (with Chinese translation).

By some reason, [Yarn package page](https://yarnpkg.com/en/package/postcss) use `README.cn.md` instead of `README.md`.

**Comment by Haroenv** [comment]
oh, thanks for noticing, I'll investigate this!

**Comment by Haroenv** [comment]
I'm closing and reopening in https://github.com/algolia/npm-search/issues/67
