### ISSUE TITLE
when i run bundle exec jekyll serve --incremental i get this error

### ISSUE THREAD

**Issue by akshayvinchurkar1** [yarnpkg/website#713]
when i run bundle exec jekyll serve --incremental i get this error

Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    File to import not found or unreadable: bootstrap/scss/bootstrap.scss. Load path: C:/Users/admin/Desktop/website/_sass on line 24

**Comment by Haroenv** [comment]
can you run `make` instead?

**Comment by akshayvinchurkar1** [comment]
i am on windows so no ```make```

**Comment by Haroenv** [comment]
The manual steps are:

```sh
git submodule update --init --recursive
bundle install
yarn install
```

and then to start:

```sh
yarn start& bundle exec jekyll serve --incremental& wait
```

Did that help?

**Comment by akshayvinchurkar1** [comment]
Cloning into 'C:/Users/admin/Desktop/website/_sass/bootstrap'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:twbs/bootstrap.git' into submodule path 'C:/Users/admin/Desktop/website/_sass/bootstrap' failed
Failed to clone '_sass/bootstrap'. Retry scheduled
Cloning into 'C:/Users/admin/Desktop/website/_sass/bootstrap'...
Host key verification failed.
fatal: Could not read from remote repository.
error after running first command

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:twbs/bootstrap.git' into submodule path 'C:/Users/admin/Desktop/website/_sass/bootstrap' failed
Failed to clone '_sass/bootstrap' a second time, aborting

**Comment by Haroenv** [comment]
I think you might need to add your ssh key to GitHub: https://github.com/settings/keys, otherwise you can change the .gitmodules to use https://github.com instead of git@

**Comment by akshayvinchurkar1** [comment]
[submodule "_sass/bootstrap"]
	path = _sass/bootstrap
	url =  https://github.com:twbs/bootstrap.git


this is correct right?

**Comment by akshayvinchurkar1** [comment]
i manually download bootstrpa and put in sass folder and then run the rest commands error

jekyll 3.2.1 | Error:  Invalid CSS after "...lor}: #{$value}": expected "{", was ";" on line 4

**Comment by Haroenv** [comment]
```
url = https://github.com/twbs/bootstrap.git
```

**Comment by akshayvinchurkar1** [comment]
still its not working

**Comment by Haroenv** [comment]
I'm sorry that I can't help you more than this, could you maybe push a repository with the bootstrap tracked so I can try it?

**Comment by Haroenv** [comment]
Otherwise you can maybe do your change without seeing how it looks, and relying on the pull request deploy preview to see the change

**Comment by Haroenv** [comment]
Please reopen if you still have that issue
