### ISSUE TITLE
[doc] Yarn website documents bundleDependencies but does not support them

### ISSUE THREAD

**Issue by iarna** [yarnpkg/website#714]
Docs are [here](https://yarnpkg.com/lang/en/docs/dependency-types/#toc-bundleddependencies)

Yarn does not support installing nor publishing bundled dependencies. Installation of a package that bundles deps will get the wrong versions. Publishing or packing of a project with bundled dependencies will result in a tarball without any of those packages in the tarball.

I'm suggesting that the documentation page should have a note that this feature is currently unsupported by yarn.

**Comment by Haroenv** [comment]
Thanks for noting this @iarna, @yarnpkg/core, do you agree that it should be removed until we support it?

**Comment by bestander** [comment]
Yeah, bundled dependencies are a trouble.
I propose just fixing them, there are some known bugs and it should be rather easy to fix them

**Comment by BYK** [comment]
@bestander totally agree and apologize for the completely misleading docs @iarna. We already have https://github.com/yarnpkg/yarn/issues/3751 but the title was not reflecting that it was all about `bundledDependencies.

I'll go ahead and close this in favor of the updated issue on the actual Yarn repo.
