### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by castelobranco** [yarnpkg/website#719]
There is a missing page on the documentation - 404 error: <https://yarnpkg.com/en/docs/managing-dependencies>.

**Comment by Haroenv** [comment]
This link seems to work for me

<img width="1028" alt="screen shot 2017-11-16 at 09 46 15" src="https://user-images.githubusercontent.com/6270048/32881913-0269feba-cab3-11e7-9595-c2e36583df39.png">

Could you try again?

**Comment by castelobranco** [comment]
Hi Haroenv, it is working now! Thanks!
