### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by jasongrout** [yarnpkg/website#720]
https://github.com/yarnpkg/website/blob/1c04a8843512d7a7bfab9beea58f63965ae22ab7/lang/en/docs/workspaces.md has a typo: `accidentaly` should be `accidentally`

**Comment by Haroenv** [comment]
Feel free to open a PR!

**Comment by jasongrout** [comment]
Thanks! I didn't think the paperwork for me to contribute to a new repo was worth the effort...
