### ISSUE TITLE
yarn add <git remote url> doesn't work

### ISSUE THREAD

**Issue by kamleshchandnani** [yarnpkg/website#721]
```yarn add <git remote url>``` throws ```error Missing list of packages to add to your project``` because yarn is identifying the characters in git URL as paramter list and it breaks after ```@``` is encountered in the the git url.

Steps to reproduce:
```yarn add -d git+https://username@bitbucket.org/projectname/repo.git```

Possible solution:
```yarn add -d -- git+https://username@bitbucket.org/projectname/repo.git``` 
```--``` marks the end of parameter and then yarn installs the package successfully.

This is happening even if we try to use ```ssh```

**Comment by bestander** [comment]
The proper flag name is `--dev` or `-D`
And this works fine:
```
yarn add -D https://github.com/stevemao/left-pad
```

**Comment by kamleshchandnani** [comment]
Avoid the typo
```yarn add -D -- git+https://username@bitbucket.org/projectname/repo.git```
This doesn’t works

**Comment by bestander** [comment]
Can you give a specific example that does not work?
I don't have a bitbucket hosted package handy.
If you do it without `-D --` part it works then?

**Comment by kamleshchandnani** [comment]
@bestander So basically what I mean is if your git repo has some special characters like '@' in this case ```yarn add -D -- git+https://username@bitbucket.org/projectname/repo.git```. If you remove ```--``` after your flag you won't be able to install the package. I have bitbucket repo but it wont work for you as its private to org
