### ISSUE TITLE
No docs page for `prune` command.

### ISSUE THREAD

**Issue by rally25rs** [yarnpkg/website#736]
```
~/Projects/yarn-test 🐒   yarn prune
yarn prune v1.3.2
error The prune command isn't necessary. `yarn install` will prune extraneous packages.
info Visit https://yarnpkg.com/en/docs/cli/prune for documentation about this command.
```

No docs page exists for this command. A quick writeup on why the prune command isn't necessary would be helpful.

**Comment by iansu** [comment]
I originally reported this in the yarn repo. It looks like this also applies to the `dedupe` and `lockfile` commands. They all link to `https://yarnpkg.com/en/docs/cli/<command>` and none of those pages exist in the docs.
