### ISSUE TITLE
How to update avatar?

### ISSUE THREAD

**Issue by u3u** [yarnpkg/website#751]
The [website](https://yarnpkg.com) displays the old avatar, while the NPM website uses the [Gravatar](https://en.gravatar.com/) avatar.
So where should I change the avatar?

**Comment by Daniel15** [comment]
It's supposed to use your GitHub avatar.

@Haroenv Do you know the caching policy on these `cloudinary.com` image URLs? I'm not familiar with this service that the Yarn site is using for resizing.

Right now, https://res.cloudinary.com/hilnmyskv/image/fetch/w_40,h_40,f_auto,q_80,fl_lossy/https://github.com/u3u.png (URL used by Yarn site) shows @u3u's old avatar, while directly going to https://github.com/u3u.png shows the new one.

**Comment by Haroenv** [comment]
Hey @u3u, if I remember correctly, we have a very long cache age. I've noticed other outdated images. @vvo, can you check what the age for the images is and if it could be changed to something more reasonable (maybe a month?)

**Comment by u3u** [comment]
@Haroenv Yes, I know there is a cache, but this cache is too long! This picture is now displayed or a few months ago! Can you provide a manual API to clear the cache? Because I often change the avatar 😂

**Comment by Haroenv** [comment]
Cache is a lot lower now
