### ISSUE TITLE
Show repository information for packages hosted on GitLab

### ISSUE THREAD

**Issue by mojavelinux** [yarnpkg/website#754]
If I publish a package to npm that's hosted on GitLab, the repository information (from the repository field in package.json) does not appear on yarnpkg.com.

Examples:

* https://yarnpkg.com/en/package/@antora/cli
* https://yarnpkg.com/en/package/semantic-release-gitlab

Yet Yarn claims to support GitLab repositories on the following page in the documentation.

https://yarnpkg.com/en/docs/package-json#toc-repository

Thus, my only option is to use the homepage field to point to the repository.

Please add support for repositories hosted on GitLab by showing the repository information on yarnpkg.com.

**Comment by Haroenv** [comment]
Hey, thanks for asking for this support, we didn’t yet add that because nobody asked for the support on the website. Do you want to contribute to adding that data? 

It’s pretty odd that the readme doesn’t display for `@antora/cli`. I’d expect it to show, but maybe there’s a bug where it will always fetch GitHub? 

EDIT: no the bug is also in npm: registry.npmjs.com/semantic-release-gitlab (they use something closed-source for showing the readme on their website 🛩)

Relevant support should be added both to the website here for:

1. stars
2. repository activity
3. prefixing of links and images in readme

To [npm-search](https://github.com/algolia/npm-search) for: 

1. changelog fetching

**Comment by mojavelinux** [comment]
Thanks for the quick response and for considering better support for packages on GitLab. GitLab is growing very rapidly in popularity, so I think this will be a welcomed enhancement. I'd be happy to help.

To clarify, I wasn't focused on the README. That's not the concern here. The concern is that the information about the repository is missing from the right-hand sidebar. Notice the difference between yarnpkg and npmjs.

* https://www.npmjs.com/package/@antora/cli
* https://yarnpkg.com/en/package/@antora/cli

There's no link to the repository on yarnpkg.

This is actually an opportunity for differentiation from npmjs.com. npmjs.com is currently showing a link which can't be navigated in the browser. yarnpkg could create a proper link to the repository on GitLab.

**Comment by mojavelinux** [comment]
Here's the repository information in package.json.

```json
  "repository": "gitlab:antora/antora",
```

**Comment by Haroenv** [comment]
Ah, that extraction is also done in `npm-search`, we can add another key `gitlabRepo` with all relevant information and display that on the site if it’s there

**Comment by leonardosnt** [comment]
@Haroenv 

I think it would be great if `npm-search` adds the '[repository](https://yarnpkg.com/en/docs/package-json#toc-repository)' key to the [Schema](https://github.com/algolia/npm-search#schema). Because, right now, if we want to add support to Gitlab, we can't. Unless we change the Algolia Schema (like adding `gitlabRepo`, as you said). By exposing the 'repository', we could handle it directly here, without the need to change the Schema every time we need to add support to a 'repository type'.

**Comment by Haroenv** [comment]
Also a good idea. Feel free to open a pr for it there and let me know if you need any testing setup

**Comment by leonardosnt** [comment]
I think just adding `repository: cleaned.repository,` here:

https://github.com/algolia/npm-search/blob/c6196be9d9a7e45f34ec9cb846287fbf6fff0b6a/formatPkg.js#L48

it would work, right?

**Comment by Haroenv** [comment]
It should definitely help. Feel free to refactor it to have the head, branch, host and path in that structure, so that we can be more flexible. Please leave the githubRepo key for now though to leave it backwards compatible.

**Comment by leonardosnt** [comment]
@Haroenv is it possible to test npm-search locally?

**Comment by Haroenv** [comment]
yes, @leonardosnt, but you'll need an Algolia account, and will need to leave out some of the values (like readme and versions) in `formatPkg`. If you give me the account + appId you're using to test, I can give you high enough limits to test it

**Comment by leonardosnt** [comment]
Great! The account's email is: **devleeo@outlook.com** and the appId is: **8F7CBTKVH9**

**Comment by Haroenv** [comment]
I added you to a testing app @leonardosnt, feel free to get back if you need any help

**Comment by leonardosnt** [comment]
I'm not sure where I can get **head** and **branch**, can you give me a hint?

The current structure looks like this:
```js
// https://github.com/webpack/webpack.git ->
{
  host: 'github.com',
  user: 'webpack',
  project: 'webpack',
  path: ''
}

// https://github.com/babel/babel/tree/master/packages/babel ->
{
  host: 'github.com',
  user: 'babel',
  project: 'babel',
  path: '/tree/master/packages/babel'
}
```

I also created some tests to make sure this is working, if you wanna see: https://gist.github.com/leonardosnt/7b1ae70f1c04b045587c73e5b2c9bcde

**Comment by Haroenv** [comment]
head is `gitHead`, branch is `gitHead || 'master'`. I just added tests in https://github.com/algolia/npm-search/pull/99 so you can add on to that setup 😄 Super work!

**Comment by leonardosnt** [comment]
The snapshot looks like this:

Note: it also includes the default **repository** keys (**type** and **url**)
```
"repository": Object {
  "branch": "8bee5877efdc84f337a56a047438b8aaac078a2d",
  "head": "8bee5877efdc84f337a56a047438b8aaac078a2d",
  "host": "bitbucket.org",
  "path": "",
  "project": "atlaskit",
  "type": "git",
  "url": "git+https://bitbucket.org/atlassian/atlaskit.git",
  "user": "atlassian",
},
```

What do you think @Haroenv ?

**Comment by Haroenv** [comment]
That seems to be good, will be useful to construct a UI from

**Comment by leonardosnt** [comment]
@Haroenv, here is the PR: https://github.com/algolia/npm-search/pull/101

**Comment by mojavelinux** [comment]
>  "url": "git+https://bitbucket.org/atlassian/atlaskit.git",

Could this be displayed on the website as https://bitbucket.org/atlassian/atlaskit? Otherwise, it wouldn't be browsable.

**Comment by leonardosnt** [comment]
**type** and **url** are exactly as defined in package.json, we just copy them. We can use **host**, **project** and **user** to create a browsable URL.

**Comment by leonardosnt** [comment]
@Haroenv We need svg icons for Gitlab (and Bitbucket), any clue where I can find them?

**Comment by Haroenv** [comment]
https://gitlab.com/gitlab-com/gitlab-artwork/blob/master/logo/logo-monocolor.svg for gitlab

https://www.atlassian.com/dam/jcr:bd56917e-e361-4f03-b672-9f5ef5b06e80/Bitbucket-blue.svg (but we need to make it mono) for bitbucket

Also run them through https://jakearchibald.github.io/svgomg/ to be sure

**Comment by Haroenv** [comment]
making a mono version now

**Comment by Haroenv** [comment]
BitBucket

```svg
<svg width="72" height="67" xmlns="http://www.w3.org/2000/svg">
  <path fill="none" d="M-1-1h74v69H-1z"/>
  <path d="M6.8 5.4a2 2 0 0 0-2 2.4l8.5 51.5a2.7 2.7 0 0 0 2.7 2.3h40.7a2 2 0 0 0 2-1.7l8.5-52.1a2 2 0 0 0-2-2.3H6.8zm35.8 37.3h-13L26 24.3h19.7l-3.1 18.4z" fill="#2684ff"/>
</svg>
```

GitLab: 

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500">
  <path d="M249.9 476.8l90.7-279.1H159.2l90.7 279.1zM32.1 197.7L4.5 282.5c-2.5 7.7.2 16.2 6.8 21l238.5 173.3L32.1 197.7zm0 0h127.1L104.6 29.6c-2.8-8.6-15-8.6-17.9 0L32.1 197.7zm435.5 0l27.6 84.8c2.5 7.7-.2 16.2-6.8 21L249.9 476.8l217.7-279.1zm0 0H340.5l54.6-168.1c2.8-8.6 15-8.6 17.9 0l54.6 168.1z"/>
</svg>
```

**Comment by leonardosnt** [comment]
Basic support is working: 
#### Search:
Gitlab
![](https://i.imgur.com/el1FwVE.png)
Bitbucket
![](https://i.imgur.com/DKMo85i.png)

#### Details:
Gitlab
![](https://i.imgur.com/0lMuqOM.png)
Bitbucket
![](https://i.imgur.com/01fYQtb.png)

**Comment by Haroenv** [comment]
Very awesome. The hard part is in rewriting the urls for README and CHANGELOG (there's actually a smaller bug there right now where a # on the same page will link to GitHub instead of locally). That logic is in Markdown.js

**Comment by leonardosnt** [comment]
@Haroenv Hey, can you update that Algolia testing app?

**Comment by Haroenv** [comment]
@leonardosnt, you can use the production app for testing the website

**Comment by leonardosnt** [comment]
@Haroenv I know, I'm using... I just needed to create some records manually, but nvm, I don't need it anymore :)

Changing the subject, there is no such **commit_activity** on Gitlab or Bitbucket, we would need to fetch hundreds kilobytes (or even megabytes, depending how large the project is) of data to just count the number commits (in order to display the graph and the _Commits last 3 months_), I don't think this we should do that...

So, should I just display the 'Last commit' in the Activity or don't display the Activity at all?

**Comment by Haroenv** [comment]
We can just fill it with whatever info we have I think

**Comment by Haroenv** [comment]
It’ll encourage someone to fill it in if they know a source

**Comment by mojavelinux** [comment]
I'm pretty sure GitLab has an activity API, which is how this screen is created:

https://gitlab.com/antora/antora/activity

I would imagine they are using https://docs.gitlab.com/ce/api/events.html#list-a-project-39-s-visible-events

**Comment by Haroenv** [comment]
@mojavelinux, the commit_activity API in GitHub is way more focused to the numbers we need to draw that graph in the sidebar, I couldn't find an API which gives info like this: 

```json
[
  {
    "days": [
      0,
      11,
      14,
      6,
      8,
      4,
      1
    ],
    "total": 44,
    "week": 1485648000
  },
  {
    "days": [
      0,
      12,
      11,
      8,
      11,
      2,
      0
    ],
    "total": 44,
    "week": 1486252800
  },
  {
    "days": [
      0,
      12,
      5,
      2,
      4,
      0,
      1
    ],
    "total": 24,
    "week": 1486857600
  },
  {
    "days": [
      3,
      0,
      7,
      14,
      12,
      5,
      0
    ],
    "total": 41,
    "week": 1487462400
  },
  {
    "days": [
      0,
      6,
      13,
      8,
      18,
      2,
      2
    ],
    "total": 49,
    "week": 1488067200
  },
  {
    "days": [
      0,
      10,
      1,
      2,
      4,
      3,
      0
    ],
    "total": 20,
    "week": 1488672000
  },
  {
    "days": [
      1,
      8,
      1,
      6,
      5,
      0,
      0
    ],
    "total": 21,
    "week": 1489276800
  },
  {
    "days": [
      2,
      4,
      6,
      3,
      4,
      6,
      1
    ],
    "total": 26,
    "week": 1489881600
  },
  {
    "days": [
      3,
      5,
      2,
      3,
      12,
      5,
      1
    ],
    "total": 31,
    "week": 1490486400
  },
  {
    "days": [
      0,
      2,
      2,
      17,
      3,
      9,
      0
    ],
    "total": 33,
    "week": 1491091200
  },
  {
    "days": [
      1,
      2,
      4,
      2,
      5,
      9,
      0
    ],
    "total": 23,
    "week": 1491696000
  },
  {
    "days": [
      1,
      6,
      19,
      10,
      9,
      6,
      2
    ],
    "total": 53,
    "week": 1492300800
  },
  {
    "days": [
      1,
      5,
      6,
      13,
      4,
      0,
      1
    ],
    "total": 30,
    "week": 1492905600
  },
  {
    "days": [
      1,
      11,
      5,
      7,
      3,
      5,
      0
    ],
    "total": 32,
    "week": 1493510400
  },
  {
    "days": [
      0,
      0,
      4,
      4,
      7,
      1,
      1
    ],
    "total": 17,
    "week": 1494115200
  },
  {
    "days": [
      0,
      0,
      1,
      4,
      2,
      1,
      1
    ],
    "total": 9,
    "week": 1494720000
  },
  {
    "days": [
      4,
      3,
      3,
      3,
      8,
      8,
      1
    ],
    "total": 30,
    "week": 1495324800
  },
  {
    "days": [
      0,
      1,
      8,
      1,
      4,
      4,
      0
    ],
    "total": 18,
    "week": 1495929600
  },
  {
    "days": [
      0,
      9,
      10,
      3,
      4,
      12,
      3
    ],
    "total": 41,
    "week": 1496534400
  },
  {
    "days": [
      0,
      2,
      3,
      7,
      6,
      4,
      0
    ],
    "total": 22,
    "week": 1497139200
  },
  {
    "days": [
      0,
      8,
      2,
      3,
      1,
      2,
      1
    ],
    "total": 17,
    "week": 1497744000
  },
  {
    "days": [
      0,
      6,
      8,
      1,
      4,
      3,
      0
    ],
    "total": 22,
    "week": 1498348800
  },
  {
    "days": [
      1,
      3,
      0,
      2,
      0,
      1,
      0
    ],
    "total": 7,
    "week": 1498953600
  },
  {
    "days": [
      2,
      1,
      5,
      4,
      10,
      1,
      0
    ],
    "total": 23,
    "week": 1499558400
  },
  {
    "days": [
      0,
      1,
      4,
      6,
      4,
      4,
      0
    ],
    "total": 19,
    "week": 1500163200
  },
  {
    "days": [
      0,
      2,
      2,
      16,
      13,
      0,
      0
    ],
    "total": 33,
    "week": 1500768000
  },
  {
    "days": [
      0,
      3,
      8,
      12,
      11,
      8,
      0
    ],
    "total": 42,
    "week": 1501372800
  },
  {
    "days": [
      0,
      3,
      6,
      4,
      3,
      3,
      1
    ],
    "total": 20,
    "week": 1501977600
  },
  {
    "days": [
      3,
      2,
      2,
      4,
      4,
      1,
      0
    ],
    "total": 16,
    "week": 1502582400
  },
  {
    "days": [
      0,
      3,
      1,
      3,
      1,
      13,
      1
    ],
    "total": 22,
    "week": 1503187200
  },
  {
    "days": [
      0,
      8,
      3,
      6,
      7,
      3,
      0
    ],
    "total": 27,
    "week": 1503792000
  },
  {
    "days": [
      0,
      0,
      2,
      12,
      3,
      5,
      1
    ],
    "total": 23,
    "week": 1504396800
  },
  {
    "days": [
      4,
      7,
      3,
      3,
      10,
      1,
      0
    ],
    "total": 28,
    "week": 1505001600
  },
  {
    "days": [
      0,
      0,
      1,
      0,
      0,
      2,
      0
    ],
    "total": 3,
    "week": 1505606400
  },
  {
    "days": [
      3,
      4,
      20,
      14,
      10,
      10,
      9
    ],
    "total": 70,
    "week": 1506211200
  },
  {
    "days": [
      4,
      31,
      12,
      6,
      5,
      8,
      1
    ],
    "total": 67,
    "week": 1506816000
  },
  {
    "days": [
      0,
      3,
      16,
      7,
      3,
      3,
      1
    ],
    "total": 33,
    "week": 1507420800
  },
  {
    "days": [
      0,
      6,
      10,
      12,
      8,
      12,
      2
    ],
    "total": 50,
    "week": 1508025600
  },
  {
    "days": [
      1,
      5,
      4,
      11,
      10,
      2,
      2
    ],
    "total": 35,
    "week": 1508630400
  },
  {
    "days": [
      0,
      2,
      9,
      3,
      15,
      11,
      7
    ],
    "total": 47,
    "week": 1509235200
  },
  {
    "days": [
      3,
      10,
      10,
      8,
      7,
      8,
      1
    ],
    "total": 47,
    "week": 1509840000
  },
  {
    "days": [
      1,
      8,
      2,
      3,
      5,
      1,
      1
    ],
    "total": 21,
    "week": 1510444800
  },
  {
    "days": [
      4,
      7,
      2,
      6,
      4,
      3,
      4
    ],
    "total": 30,
    "week": 1511049600
  },
  {
    "days": [
      2,
      8,
      15,
      12,
      18,
      5,
      3
    ],
    "total": 63,
    "week": 1511654400
  },
  {
    "days": [
      0,
      5,
      6,
      2,
      10,
      6,
      2
    ],
    "total": 31,
    "week": 1512259200
  },
  {
    "days": [
      3,
      3,
      4,
      2,
      0,
      1,
      0
    ],
    "total": 13,
    "week": 1512864000
  },
  {
    "days": [
      1,
      3,
      1,
      0,
      0,
      1,
      4
    ],
    "total": 10,
    "week": 1513468800
  },
  {
    "days": [
      7,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "total": 7,
    "week": 1514073600
  },
  {
    "days": [
      0,
      0,
      3,
      5,
      4,
      13,
      2
    ],
    "total": 27,
    "week": 1514678400
  },
  {
    "days": [
      5,
      1,
      5,
      2,
      5,
      0,
      0
    ],
    "total": 18,
    "week": 1515283200
  },
  {
    "days": [
      1,
      1,
      1,
      1,
      2,
      2,
      0
    ],
    "total": 8,
    "week": 1515888000
  },
  {
    "days": [
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "total": 0,
    "week": 1516492800
  }
]
```

(we're limiting what we use from that to the `total` from each week in the last 3 months, but another fidelity could also work)

**Comment by mojavelinux** [comment]
Ah, I see. You are looking more for a summary. Once we can demonstrate support for GitLab on yarkpkg.com, we may be able to convince them to add such a feature. I'll file an issue if need be once we get to that stage.

**Comment by mojavelinux** [comment]
As a user of yarnpkg.com, I'll share that the most useful bit of information is when did the last commit happen. That speaks volumes. I can use that to quickly determine if a project is alive at all or not.

**Comment by leonardosnt** [comment]
I think it is done. 🎉 

Bitbucket example package
![localhost_4000_lang_en_package__atlassian-connect-express](https://user-images.githubusercontent.com/13869336/35240504-caf781ba-ff9a-11e7-9454-e9b1bde681db.png)
Gitlab example package
![localhost_4000_lang_en_package__semantic-release-gitlab](https://user-images.githubusercontent.com/13869336/35240505-cb1ca63e-ff9a-11e7-83ad-f6c35da7e4b4.png)

**Comment by Haroenv** [comment]
Awesome 😎 looking forward to your PR

**Comment by leonardosnt** [comment]
Here is the comparison, if you wanna take a look. https://github.com/yarnpkg/website/compare/master...leonardosnt:gitlab-bitbucket-support
I just need to finish these TODOs:
https://github.com/leonardosnt/website/blob/ddb6841a08b07b43fc5b21d96f3166ef87bf92b7/js/src/lib/Details/Links.js#L31
https://github.com/leonardosnt/website/blob/ddb6841a08b07b43fc5b21d96f3166ef87bf92b7/js/src/lib/Search/index.js#L80

**Comment by Haroenv** [comment]
First todo: what about simply linking it in that case? Can be improved later I guess, people will see it’s an unknown provider (we can use the git icon for it) and won’t expect to be able to browse it simply, but it would fallback nicely I think, copying the url for example

**Comment by leonardosnt** [comment]
@Haroenv Ok, we just need a git icon.

**Comment by mojavelinux** [comment]
This is looking fantastic. I'm so excited about this. :tada: 

I have one request which I hope isn't too major. For a package hosted on GitHub, yarnpkg shows the name + avatar for the owning organization next to the package name. For example, the [mocha package](https://github.com/mochajs/mocha) shows the name + avatar for [mochajs](https://github.com/mochajs/mocha) (instead of the person who last released it, like [npmjs does](https://www.npmjs.com/package/mocha)). Based on the screenshots above, it appears as though a package hosted on BitBucket or GitLab is still showing the name + avatar of the person who released the package. I really like that yarnpkg hides the person who last released it in favor of the package owner. Could we have the same for BitBucket and GitLab-hosted packages?

For the semantic-release-gitlab, I would expect it to show hyper-expanse instead of hbetts.

**Comment by leonardosnt** [comment]
@mojavelinux The only problem is that we need to make API calls (two if the repo is owned by a group`*`, one if is by a user) to fetch the avatar`**`, and since there are hundreds of thousands packages, the rate limit would be exceeded pretty quickly.

`*` https://gitlab.com/gitlab-org/gitlab-ce/issues/39858
`**` https://github.com/algolia/npm-search/blob/master/src/formatPkg.js#L148

**Comment by mojavelinux** [comment]
So if I understand correctly, since GitLab doesn't have an avatar shortlink like GitHub, then the API calls are necessary. Is that correct?

I'm not so concerned about the image. I'm more concerned that the name is correct. I like that yarnpkg emphasizes the owner instead of the releaser. Otherwise, it makes it look like the package is changing ownership all the time (in the case there are different people releasing).

**Comment by Haroenv** [comment]
Seems like they use gravatar, combined with some upload system. I agree with @mojavelinux that the repository owner is more important than the npm owner and we should show it for gitlab too. Can you send an email to gitlab and bitbucket support to see if it's possible? Anyway, I think we can still add that improvement later (incremental improvements > big improvements IMO)

**Comment by leonardosnt** [comment]
@mojavelinux Exactly!
@Haroenv Sure, I'll send the email.

**Comment by mojavelinux** [comment]
I just noticed today that this change is live! Thank you so much for your work on this feature. It really means a lot! I'll be sure to promote far and wide.

See https://yarnpkg.com/en/package/@antora/cli for an example.

**Comment by Haroenv** [comment]
Yes, I think all major stuff is merged here. You can open new issues for smaller things you notice or suggest. Lovely community work happened here :)

**Comment by mojavelinux** [comment]
> Lovely community work happened here :)

The very best. Thanks @leonardosnt!!!
