### ISSUE TITLE
Install script should check for expected GPG subkeys

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/website#761]
See https://github.com/yarnpkg/yarn/issues/5223

Currently it just checks for the main GPG key, but that doesn't handle if we've recently rotated the subkeys. It should check that the proper subkey is present, too.

**Comment by cormacrelf** [comment]
FYI, this is still happening. https://travis-ci.org/cormacrelf/angular-skyhook/builds/415030644

That CI has been installing yarn via install.sh for about a month.

**Comment by Daniel15** [comment]
I don't think that's the same issue that was covered here. Please open a new issue if you still see this. Note that ideally you should use Docker for system-wide dependencies such as Yarn, rather than installing it fresh on every single build. It'd speed up your builds, too :)
