### ISSUE TITLE
Algolia search requests error with "ObjectID does not exist"

### ISSUE THREAD

**Issue by wopian** [yarnpkg/website#773]
Searching for a package or opening the package page returns no results. The requests to Algolia fail with the following:

```json
{
"message": "ObjectID does not exist",
"status": 404
}
```

https://yarnpkg.com/en/packages?q=babel
![](https://i.imgur.com/6RLtXf1.png)

https://yarnpkg.com/en/package/babel
![](https://i.imgur.com/pde9q9K.png)

**Comment by Haroenv** [comment]
The search is currently down due to a bug in the indexing process which deleted the wrong index. 

Currently busy adding a notice to the site, ETA for the fix to propagate the index is ±7h now

https://twitter.com/haroenv/status/963077429278466048

**Comment by wopian** [comment]
Fix has propagated 👍

**Comment by Haroenv** [comment]
Yep, confirming all is fine now
