### ISSUE TITLE
Contributing page

### ISSUE THREAD

**Issue by jamiebuilds** [yarnpkg/website#8]
Would be good to put on the site since it can be translated.

Starting point: https://github.com/yarnpkg/yarn/blob/master/CONTRIBUTING.md

**Comment by chuwik** [comment]
Related: made a simple change in #160 to use 'yarn run' for the commands rather than 'npm run'.

**Comment by edmorley** [comment]
This can be closed, since was fixed by #699 and yarnpkg/yarn#4872.
