### ISSUE TITLE
article about yarn search

### ISSUE THREAD

**Issue by transitive-bullshit** [yarnpkg/website#800]
Just wanted to give a shout to you guys for all your hard work -- I wrote an [article](https://hackernoon.com/mastering-the-art-of-npm-ca06357150cb) with the main focus being the benefits of using Yarn's Algolia-powered search as I believe it's the best way to search npm.

Hope someone finds this plug helpful!

**Comment by Haroenv** [comment]
Really nice article, thanks for writing it!, @yarnpkg/core, can someone tweet about this maybe?

**Comment by Haroenv** [comment]
https://twitter.com/haroenv/status/980521101754167296 (retweeted by Yarn), thanks!

**Comment by transitive-bullshit** [comment]
Thanks!
