### ISSUE TITLE
Peer Dependency Clarification

### ISSUE THREAD

**Issue by bwiggs** [yarnpkg/website#805]
I'm trying to wrap my head around what a peer dependency is and came across this definition from the yarn docs.

"Having a peer dependency means that your package needs a dependency that is the same exact dependency as the person installing your package."

Specifically what does "same exact dependency as the person installing your package" mean? 

Additional clarifications around peer dependencies and when I would want to use one would be much appreciated!

**Comment by Daniel15** [comment]
npm have a good description on their blog: https://nodejs.org/en/blog/npm/peer-dependencies/. Also see https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/ ("peer dependencies" section).

I agree that the text on the Yarn site needs to be extended a bit.

**Comment by Daniel15** [comment]
Fixed by #809, thanks @arcanis!

https://yarnpkg.com/blog/2018/04/18/dependencies-done-right/
