### ISSUE TITLE
Searching for packages from blog leads to 404

### ISSUE THREAD

**Issue by SimenB** [yarnpkg/website#810]
![untitled](https://user-images.githubusercontent.com/1404810/38974459-8a73ea4e-43aa-11e8-9acd-5dd9333f912f.gif)

Miiight be related to (the solution for) #385, but my browser is in English, so I can't reproduce that issue.

**Comment by Haroenv** [comment]
Yes, maybe te link in blog should be /en/ blog so urls work as expected, I’ll close this one as it’s indeed a duplicate, I just haven’t found the time fixing this yet
