### ISSUE TITLE
No Documentation for `yarn workspaces`

### ISSUE THREAD

**Issue by jahed** [yarnpkg/website#815]
Similar to #563 but for `yarn workspaces` (note the 's').

I'd expect the page to be here: https://yarnpkg.com/en/docs/cli/workspaces

I would've made a simple PR for this (afaik there's only a `info` subcommand), but I can't get the project to build on Windows.

**Comment by Haroenv** [comment]
Feel free to make a PR without actually building the project; it deploys to a staging website on PR, so we can review there :)
