### ISSUE TITLE
docs: adds a section on the possibility of configuring npm via env vars

### ISSUE THREAD

**Issue by owayss** [yarnpkg/website#842]
Hi everyone :wave:

I noticed that Yarn has this feature which exposes `npm_config` env variables to lifecycle scripts, making it possible to configure `npm`:
https://github.com/yarnpkg/yarn/blob/master/src/registries/npm-registry.js#L268

My particular use case was passing down `npm_config_build_from_source=true` in order to force building packages from sources instead of falling back to pre-compiled binary in case they existed.

I have looked around the docs and found no mention of `npm_config`, but I could be wrong. In any case, I have sent a small doc PR (https://github.com/yarnpkg/website/pull/841) to add a section on configuring npm in the envvars page.

Cheers!

**Comment by Haroenv** [comment]
Thanks for the PR!
