### ISSUE TITLE
Error w/ installing `yarn` via Debian

### ISSUE THREAD

**Issue by naganowl** [yarnpkg/website#845]
I've been following the instructions on https://yarnpkg.com/en/docs/install#debian-stable to install `yarn` on CircleCI. It's been working flawlessly until today where I ran into issues with the distribution source files being [missing](https://gist.github.com/naganowl/32015225152e11b92bf3a574cf38a767#file-yarn-install-error-log-L478-L485).

At the time of writing, it appears that http://ppa.launchpad.net/pdoes/ppa/ubuntu/dists/ is missing the directory being looked for. Can the link in the package repository be updated to resolve this?

**Comment by Daniel15** [comment]
>  it appears that http://ppa.launchpad.net/pdoes/ppa/ubuntu/dists is missing the directory being looked for

This PPA is not related to Yarn. You should determine which packages you're using from this PPA, and either contact its owner, or remove it from your config. The **only** package repository that Yarn uses (in addition to the regular Debian one) is at `dl.yarnpkg.com`.
