### ISSUE TITLE
Document audit command

### ISSUE THREAD

**Issue by gabegorelick** [yarnpkg/website#877]
When `yarn audit` encounters an error, it says "Visit https://yarnpkg.com/en/docs/cli/audit for documentation about this command." But https://yarnpkg.com/en/docs/cli/audit returns a 404.

![image](https://user-images.githubusercontent.com/610129/47800089-99cb3900-dcf9-11e8-83eb-6a0de4dccbbe.png)

![image](https://user-images.githubusercontent.com/610129/47800079-93d55800-dcf9-11e8-8ce3-742e9952ac86.png)

**Comment by Haroenv** [comment]
@arcanis @rally25rs, do we have some documentation somewhere hidden that we can put on the website?

**Comment by rally25rs** [comment]
oops, totally forgot to write docs. I fail 😞 
I'll write something up this evening.

**Comment by rally25rs** [comment]
Docs PR: https://github.com/yarnpkg/website/pull/878
