### ISSUE TITLE
`brew install yarn --without-node` no longer possible

### ISSUE THREAD

**Issue by rdmurphy** [yarnpkg/website#913]
[As of six days ago](https://github.com/Homebrew/homebrew-core/pull/36222) Yarn's recommended install method via Homebrew has been removed because Homebrew is [doing away with options in all core formulae](https://github.com/Homebrew/homebrew-core/issues/31510). (I kinda get the rationale, but, uh... yanking out the carpet from under everyone.)

Obviously there's a bigger issue here (what is the new recommended way to install Yarn on MacOS?) but currently that means what's in the docs is no longer valid. 😬

**Comment by Haroenv** [comment]
That’s unfortunate! I think in the meantime the regular fallback installation method listed on “Linux” is a good alternative. Looks like the home brew thread isn’t fully resolved for now and anyone interested in the yarn use case can chime in there. Cc @daniel15

**Comment by Daniel15** [comment]
I'd be happy with someone modifying the site to show the shell script above the Homebrew instructions in the MacOS installation instructions. The RC and Nightly instructions already do that, so you can just copy what they're doing (eg. see https://yarnpkg.com/en/docs/install#mac-rc)

**Comment by brendanfalkowski** [comment]
Literally every time I have to use `brew` it blows up in my face. The curl method worked for me and (hopefully) associates properly to the `nvm`-selected version of Node.

**Comment by fab1o** [comment]
Try: `brew install yarn --ignore-dependencies`

**Comment by brendanfalkowski** [comment]
Just for a sanity check, if I installed Yarn last week using: `curl -o- -L https://yarnpkg.com/install.sh | bash`

And today I ran: `brew install yarn --ignore-dependencies`

Do I now have two instances installed?

Running `which yarn` returns `/Users/brendan/.yarn/bin/yarn`. Should I expect to see something different from the Homebrew installation?

**Comment by rdmurphy** [comment]
@brendanfalkowski You probably do — `brew` will install `yarn` in a different place that's standard for `brew` installs.

What happens when you run `which -a yarn`? I *think* you'll see both of them. (I think you'll see the Homebrew one at `/usr/local/bin/yarn`.)

**Comment by dorokei** [comment]
I ran: ``brew install yarn --ignore-dependencies``

Installing yarn without node was successful.
But ``brew doctor`` showed below warning.

```
Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install node

Run `brew missing` for more details.
```

I use ``nodebrew`` to manage node version. And ``yarn`` command is running normally.
Is there anyone who has same error?

**Comment by dorokei** [comment]
Sorry, I solved this warning. Create symbol link from `/usr/local/Cellar/node` to current node's global version.

**Comment by jonleopard** [comment]
I'm using `nvm` and I'm still getting the following error from `brew doctor`:

```
Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies: 
  brew install node
Run `brew missing` for more details.
```

I found one solution [here](https://gist.github.com/nijicha/e5615548181676873118df79953cb709) that suggested creating node directory and symlinking it to your nvm directory like so:

```
mkdir /usr/local/Cellar/node
ln -s ~/.nvm/versions/node/{your_node_version)/usr/local/Cellar/node
```
This didn't work for me. Plus, having to create a new symlink each time I want to change my node version would be sort of a pain as well. Was pretty happy with how things were working before this change. 

Have any `nvm` users found a way to handle this dynamically?

**Comment by Loyalsoldier** [comment]
@jonleopard 

Use [n-install](https://github.com/mklement0/n-install) instead of `nvm`

**Comment by joelgetaction** [comment]
How do I upgrade yarn without installing dependencies?  I originally installed yarn using `brew install yarn --ignore-dependencies` but `brew upgrade` does not accept the `--ignore-dependencies` flag and it is stubbornly insisting on installing `node` in brew which I do ***NOT** want as I manage node using nvm.

Do I really need to uninstall yarn and then re-install just so I can upgrade yarn without brew forcing node on me when I don't want it? :-(

**Comment by Daniel15** [comment]
@joelgetaction 	That's a question for Homebrew. The Yarn team can't really do anything about how Homebrew is handling the Node.js dependency.

**Comment by AGutierrezR** [comment]
@jonleopard 

Follow @Loyalsoldier advise, `n` is much easier in manages node versions and you can change the version of NodeJS without affecting yarn, as long as it will be a version of NodeJS that supports yarn.

Use this [link](https://gist.github.com/AGutierrezR/2c22fdd8686e6e30c56949f5e37e214e#file-install_n_nodejs_and_yarn_using_homebrew-md) to setup everything

**Comment by abumalick** [comment]
`rm /usr/local/bin/node` working for me

I user asdf to handle my nodejs versions

**Comment by gihrig** [comment]
I guess the yarn/homebrew folks just aren't going to fix this. :-/

Here's my solution, which worked on macOS El Capitan and Mojave:

`brew remove yarn` Note that you can't just `brew remove node` because yarn depends on it.
'brew remove node` brew does not remove node with yarn. This will not remove node installed by n.

This may be anathema to some, but...
`npm i -g yarn` - End of story! :-D

**Comment by bfricka** [comment]
@gihrig They did, but then [this commit](https://github.com/yarnpkg/website/commit/e4714a3d1dad66b04f7c024543ab796a4d2af06a#diff-cea4b94f43b7088cd2dcd27f4273b623) reverted the workaround documentation, so we're back to:
```
curl -o- -L https://yarnpkg.com/install.sh | bash
```
It would be useful if this were added to the docs and supported moving forward.

**Comment by gihrig** [comment]
@bfricka Yes, is just a simple install, something developer folks have been doing successfully for ages. I don't see why the interest in Homebrew (or Mac Ports for that matter). npm or curl do the job quickly and efficiently.

After all, isn't 'quick and efficient' the main selling point for Yarn in the first place?

The workaround, reverted in the commit you linked, was required do to changes made by Homebrew.

As mentioned above by @rdmurphy, Homebrew decided to Remove all options from [Homebrew/homebrew-core formulae #31510](https://github.com/Homebrew/homebrew-core/issues/31510). This seems to be the beginning of this mess. I just don't understand why the simpler (superior?) methods (npm and curl) that "just work" can't become the officially supported install methods.

For anyone interested, this issue dates back to 2016 (!), just search issues for "Homebrew". By much of the info and opinions expressed, I don't expect this issue to be resolved by the current Yarn crew.

Sad, really.

**Comment by Haroenv** [comment]
The website is open source, feel free to add a PR, but installing Yarn via homebrew without node is not in the homebrew philosophy, and won't be possible in any way. The regular script works just as well, and is mentioned (since now) on the Mac installation page.

**Comment by bfricka** [comment]
@Haroenv Great news! I definitely understand the rationale behind not using a Homebrew developer hack. If you want to use Homebrew to install Yarn, do it the Homebrew way. Thank you for addressing this in the documentation.

**Comment by dstroot** [comment]
Installing Node, NPM and Yarn via homebrew has been "more than a challenge" for some time now using homebrew.  I am giving up and writing my own scripts outside of homebrew now which defeats the purpose of using my brewfile to install all my laptop's extra SW.  It's incredibly frustrating that we can't have separate installers for Node, NPM and Yarn with no dependencies and those of us who use N or NVM to manage Node versions could just choose what package manager we want (NPM or Yarn) install it and move along.  But no.....

**Comment by Haroenv** [comment]
there's *no* way to install via Homebrew without also installing Node. this is a limitation of Homebrew itself and can not be solved by us.

Your options are:

1. use the script: https://yarnpkg.com/en/docs/install#mac-stable

```
curl -o- -L https://yarnpkg.com/install.sh | bash
```

2. use npm

https://yarnpkg.com/en/docs/install#alternatives-stable

3. arguing about this with Homebrew maintainers

This has already been done countless times, all linked throughout this thread
