### ISSUE TITLE
indexof package not visible

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/website#915]
This works: https://www.npmjs.com/package/indexof
This doesn't: https://yarnpkg.com/en/package/indexof

@Haroenv?

**Comment by Haroenv** [comment]
Hmm, that’s odd. Discrepancies are possible on recent packages but an old one like this is unexpected. I wonder if the name might cause a problem. A reminded is currently busy so in I think about 24h we can see if it’s a permanent problem

**Comment by Haroenv** [comment]
Actually it's a permanent problem, and probably one of the 1500 packages listed on http://search-status.yarnpkg.com

If we look at its registry file: http://registry.npmjs.org/indexof, it's clear that we discard it wrongly in the indexing process because it has no author.

```json
{
  "_id": "indexof",
  "_rev": "5-3fd826d99ea92eb0a3423197ec995629",
  "name": "indexof",
  "description": "Microsoft sucks",
  "dist-tags": { "latest": "0.0.1" },
  "versions": {
    "0.0.1": {
      "name": "indexof",
      "description": "Microsoft sucks",
      "version": "0.0.1",
      "keywords": ["index", "array", "indexOf"],
      "dependencies": {},
      "component": { "scripts": { "indexof/index.js": "index.js" } },
      "_id": "indexof@0.0.1",
      "dist": {
        "shasum": "82dc336d232b9062179d05ab3293a66059fd435d",
        "tarball": "https://registry.npmjs.org/indexof/-/indexof-0.0.1.tgz"
      },
      "maintainers": [
        { "name": "tjholowaychuk", "email": "tj@vision-media.ca" }
      ],
      "directories": {}
    }
  },
  "readme": "\n# indexOf\n\n  Lame indexOf thing, thanks microsoft\n\n## Example\n\n```js\nvar index = require('indexof');\nindex(arr, obj);\n```\n\n## License\n\n  MIT",
  "maintainers": [{ "name": "tjholowaychuk", "email": "tj@vision-media.ca" }],
  "time": {
    "modified": "2015-02-15T11:58:00.609Z",
    "created": "2012-08-31T16:20:13.243Z",
    "0.0.1": "2012-08-31T16:20:14.894Z"
  },
  "users": { "pnevares": true, "synchronous": true },
  "keywords": ["index", "array", "indexOf"],
  "readmeFilename": "",
  "_attachments": {}
}
```

Our logic of inferring the author should take `maintainers` also in account, since likely that was the original required key.

```js
  if (!githubRepo && !lastPublisher && !author) {
    return undefined; // ignore this package, we cannot link it to anyone
  }
```
https://github.com/algolia/npm-search/blob/dbb7b98bcf374a086a5bbc9753985a5b40810e2c/src/formatPkg.js#L34-L36

**Comment by Haroenv** [comment]
After next bootstrap I expect `indexof` to be included, and the 1542 packages missing to be significantly lower

**Comment by Haroenv** [comment]
there's been a new index, and this indeed made the https://yarnpkg.com/en/package/indexof package show again. Now the discrepancy is only 200 packages, and no longer 1500 :)

**Comment by Daniel15** [comment]
Great, thanks @Haroenv!
