### ISSUE TITLE
self-update should be removed

### ISSUE THREAD

**Issue by arcanis** [yarnpkg/website#918]
The `self-update` command doesn't exist and its use case is fulfilled by `yarn policies set-version`. We should remove it from the documentation.

https://yarnpkg.com/en/docs/cli/self-update

**Comment by Haroenv** [comment]
Accidentally committed instead of making a PR, but seems fine to me

**Comment by MiroslavPetrik** [comment]
@Haroenv I think that https://github.com/yarnpkg/website/commit/4179672117d8cb188453d7ca3d8357364c6c4579 is not sufficient fix for this and instead the `self-update` page should be removed completely.

Also it shouldn't be in the navigation/command list as it's not listed by the `yarn -h` command.

When you google `yarn update` you get this page of non-existing command as a 2nd result.
I would expect to see link to `https://yarnpkg.com/en/docs/install#mac-stable` section `Upgrade yarn`.

What do you think about it? Can the update/upgrade experience be improved?
