### ISSUE TITLE
gitlab-ci example for cache

### ISSUE THREAD

**Issue by punkkk** [yarnpkg/website#928]
https://yarnpkg.com/lang/en/docs/install-ci/

gitlab tab is empty. 
![image](https://user-images.githubusercontent.com/4415815/53818262-7a2a7280-3f70-11e9-9db1-88a99161bf62.png)
![image](https://user-images.githubusercontent.com/4415815/53818295-84e50780-3f70-11e9-8eb6-c4d5a7ee7c3b.png)

**Comment by Haroenv** [comment]
thanks for opening an issue, I was aware and mentioned my wrong fix in #922

**Comment by Haroenv** [comment]
I think I fixed this in https://github.com/yarnpkg/website/commit/c864b56045276ac58b4cd76bf1f84af4d6f33511

https://app.netlify.com/sites/yarnpkg/deploys/5c7eac06b1c7b8000a9c1c8d to see progress

**Comment by Haroenv** [comment]
This was indeed fixed

**Comment by punkkk** [comment]
Thanks for quick fix, but it seems not complete.

Gitlab ci will delete all ignored files by git, and node_modules usually is in .gitignore, so probably you will need to use:

```
cache:
  untracked: true
```
Bcs by default gitlab will delete all ignored files and dirs. But it is not complete solution too, due to cache is for whole project, multiple branches can rewrite it, so better to use `key` field with branch reference to prevent package versions conflicting between branches.

Simple example with key's value is [here](https://docs.gitlab.com/ee/ci/caching/index.html#caching-nodejs-dependencies)

For whole project seems wise to use yarn cache mechanism and caching yarn's cache folder for whole project too.

**Comment by Haroenv** [comment]
I was only talking about the content for the file showing up; not the content of the file itself. Please make a PR to https://github.com/yarnpkg/website/blob/master/lang/en/docs/_ci/gitlab.md with any fixes you have
