### ISSUE TITLE
Semaphore Classic doc update

### ISSUE THREAD

**Issue by csidyel** [yarnpkg/website#932]
Hi,

I'd like to propose a doc update for https://yarnpkg.com/lang/en/docs/install-ci/ regarding Semaphore Classic to the following:

```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
# install-package is a tool for caching APT installations in Semaphore
# defining a package version is optional
install-package --update-new yarn
```
Because manually specifying Yarn version does not work. 
Thanks!

**Comment by Haroenv** [comment]
In that case, the "version" comment probably also should be removed.

cc @ervinb and @lesleh who contributed on this page

**Comment by lesleh** [comment]
Specifying the version does appear to work but the format has to be (for example) `1.12.3-1` instead of simply `1.12.3`, the former will fail to install.

**Comment by csidyel** [comment]
@lesleh I've tested it and it works like a charm. Thanks!
