### ISSUE TITLE
Markdown showing up in code block on CI page in docs

### ISSUE THREAD

**Issue by sweepyoface** [yarnpkg/website#940]
The [source](https://github.com/yarnpkg/website/blob/1200d77e43bae633bf1de46e9af54770f583f524/lang/en/docs/_ci/gitlab.md) looks fine, but in the GitLab tab of [this page](https://yarnpkg.com/lang/en/docs/install-ci/), the top line of Markdown is being displayed as code.

![image](https://user-images.githubusercontent.com/7191851/55360607-e67e9000-54a2-11e9-9058-206126ad519c.png)

**Comment by Haroenv** [comment]
This is weird! I don't see any explanation for this behaviour, but luckily it's not incredibly disturbing. I think it's fine for now, maybe it's something that only happens once?
