### ISSUE TITLE
Homepage's full content: Click here to see the site

### ISSUE THREAD

**Issue by Walfisch** [yarnpkg/website#992]
Reproduce:

0. Use firefox
1. Go to `https://yarnpkg.com/`
2. Look at the homepage's full content `Click here to see the site`

```
$ curl https://yarnpkg.com/
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="refresh" content="0;URL='lang/en/'" />
    <title></title>
  </head>
  <body>
    <a href="lang/en/">Click here to see the site</a>
  </body>
</html>
```

Why is the homepage trying to immediately redirect?

**Comment by Haroenv** [comment]
That page should only be seen as a last fallback, and should normally redirect based on language accept headers. Do you know which language accept headers you have enabled?

**Comment by Walfisch** [comment]
ah, interesting.  
sure, here (pasted some more):  

<table>
<tr>
<td>USER-AGENT
<td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:69.0) Gecko/20100101 Firefox/69.0
<tr>
<td>ACCEPT
<td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
<tr>
<td>ACCEPT-LANGUAGE
<td>de,en;q=0.5
<tr>
<td>ACCEPT-ENCODING
<td>gzip, deflate, br
</table>

**Comment by Haroenv** [comment]
hmm, since you accept English, it should have gone there by default, but maybe it didn't because it's not in first position. For what it's worth, I don't see that page going to the website on a fresh browser, and when I curl I get 301 moved permanently

```
HTTP/1.1 301 Moved Permanently
Date: Fri, 09 Aug 2019 08:03:10 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Fri, 09 Aug 2019 09:03:10 GMT
Location: https://yarnpkg.com/
Server: cloudflare
CF-RAY: 50383645cbfecde3-CDG
```

**Comment by Walfisch** [comment]
Wow, changing the order of my lang settings does have an impact

en,de -> 302
```
$ curl -I -H'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:69.0) Gecko/20100101 Firefox/69.0' -H'Accept-Language: en,de;q=0.5' -H'Accept-Encoding: gzip, deflate, br' https://yarnpkg.com
HTTP/2 302
date: Fri, 09 Aug 2019 10:07:53 GMT
content-type: text/plain; charset=utf-8
content-length: 20
set-cookie: __cfduid=db427d798d45fcbbe0ee1b9a31988c3bd1565345273; expires=Sat, 08-Aug-20 10:07:53 GMT; path=/; domain=.yarnpkg.com; HttpOnly
cache-control: public, max-age=0, must-revalidate
location: /en/
age: 560
x-nf-request-id: 523e86b4-7c49-4de3-83fa-58e4e1167ce7-2674877
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5038ecf61e817cf4-MUC
```

de,en -> 200
```
$ curl -I -H'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:69.0) Gecko/20100101 Firefox/69.0' -H'Accept-Language: de,en;q=0.5' -H'Accept-Encoding: gzip, deflate, br' https://yarnpkg.com
HTTP/2 200
date: Fri, 09 Aug 2019 10:08:34 GMT
content-type: text/html; charset=UTF-8
set-cookie: __cfduid=de271e303b21c3e2eb0f67bec5af4c64a1565345314; expires=Sat, 08-Aug-20 10:08:34 GMT; path=/; domain=.yarnpkg.com; HttpOnly
cache-control: public, max-age=0, must-revalidate
age: 372
vary: Accept-Encoding
x-nf-request-id: 917a8150-36e1-4569-aabf-f673a892fbf0-632175
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5038edf8fb307d06-MUC
content-encoding: gzip
```

I leave it to you, if you want to close the ticket or look into it.  
Thanks so far!

**Comment by Haroenv** [comment]
I’ll look into the redirects, it might be set up to look only at one, but in that case it can still redirect to English, not the homepage

**Comment by Walfisch** [comment]
Does not happen anymore
