### ISSUE TITLE
French installation guide is not up to date

### ISSUE THREAD

**Issue by zekth** [yarnpkg/website#993]
On the french installation page : https://yarnpkg.com/lang/fr/docs/install/#mac-stable we can see for brew installation:
`brew install yarn --without-node`
which is deprecated now. See the english page:
https://yarnpkg.com/en/docs/install#mac-stable

**Comment by Haroenv** [comment]
please contribute on http://i18n.yarnpkg.com

**Comment by zekth** [comment]
> please contribute on http://i18n.yarnpkg.com

Sorry another tool, another registration, not for me. If someone would want to do this feel free to do it. Was just a notice.
